/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `OpenSpec の変更からタスクを実装します。

${STORE_SELECTION_GUIDANCE}

**入力**: 必要に応じて、変更名を指定します。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更を選択**

名前が指定されている場合は、それを使用します。さもないと：
- ユーザーが変更について言及したかどうかを会話のコンテキストから推測します
- アクティブな変更が 1 つだけ存在する場合は自動選択
- 曖昧な場合は、\`openspec list --json\` を実行して利用可能な変更を取得し、**AskUserQuestion ツール**を使用してユーザーに選択させます。

常に「変​​更の使用: <name>」と上書き方法 (例: \`/opsx:apply <other>\`) をアナウンスします。

2. **ステータスを確認してスキーマを理解します**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
JSON を解析して以下を理解します。
- \`schemaName\`: 使用されているワークフロー (例: 「仕様主導」)
- \`planningHome\`、\`changeRoot\`、および \`actionContext\`: 計画範囲と編集制約
- どのアーティファクトにタスクが含まれているか (通常、仕様主導型の場合は「タスク」、その他の場合はステータスを確認)

3. **適用手順を取得**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

これは以下を返します:
- \`contextFiles\`: アーティファクト ID -> 具体的なファイル パスの配列 (スキーマによって異なります - 提案/仕様/設計/タスクまたは仕様/テスト/実装/ドキュメントの可能性があります)
- 進行状況 (合計、完了、残り)
- ステータス付きタスクリスト
- 現在の状態に基づいた動的な命令

**ハンドル状態:**
- \`state: "blocked"\` (アーティファクトが欠落している) の場合: メッセージを表示し、openspec- continue-change の使用を提案します。
- \`state: "all_done"\` の場合: おめでとうございます、アーカイブを提案してください
- それ以外の場合: 実装に進みます。

4. **コンテキスト ファイルの読み取り**

適用命令の出力から、\`contextFiles\` の下にリストされているすべてのファイル パスを読み取ります。
ファイルは使用されているスキーマによって異なります。
- **仕様主導**: 提案、仕様、設計、タスク
- その他のスキーマ: CLI 出力の contextFiles に従います。

5. **現在の進行状況を表示**

画面：
- 使用されているスキーマ
- 進行状況: 「N/M 個のタスクが完了しました」
- 残りのタスクの概要
- CLIからの動的指示

6. **タスクを実装します (完了またはブロックされるまでループします)**

保留中のタスクごとに次のようにします。
- どのタスクが進行中かを表示します
- 必要なコード変更を行う
- 変更を最小限に抑え、焦点を絞ったものにします
- タスク ファイルでタスクを完了としてマークします: \`- [ ]\` → \`- [x]\`
- 次のタスクに進む

**次の場合は一時停止します**
- タスクが不明瞭 → 説明を求める
- 実装により設計上の問題が明らかになった → アーティファクトの更新を提案
- エラーまたはブロッカーが発生しました → 報告してガイダンスを待ちます
- ユーザーによる割り込み

7. **完了または一時停止時にステータスを表示**

画面：
- このセッションでタスクが完了しました
- 全体的な進捗状況: 「N/M 個のタスクが完了しました」
- すべて完了したら: アーカイブを提案します
- 一時停止した場合: 理由を説明し、指示を待ちます

**実装時の出力**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**完了時の出力**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Ready to archive this change.
\`\`\`

**一時停止時の出力 (問題が発生しました)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**ガードレール**
- 完了するかブロックされるまでタスクを実行し続けます
- 開始する前に必ずコンテキスト ファイルを読み取ります (適用命令の出力から)。
- タスクがあいまいな場合は、実行する前に一時停止して質問してください
- 実装で問題が明らかになった場合は、一時停止してアーティファクトの更新を提案します
- コードの変更を最小限に抑え、各タスクの範囲に限定します
- 各タスクが完了したらすぐに「タスクを更新」チェックボックスをオンにします
- エラー、阻害要因、または不明瞭な要件がある場合は一時停止します - 推測しないでください
- CLI 出力から contextFiles を使用し、特定のファイル名を想定しないでください。

**流動的なワークフローの統合**

このスキルは、「変更に対するアクション」モデルをサポートします。

- **いつでも呼び出すことができます**: すべてのアーティファクトが完了する前 (タスクが存在する場合)、部分的な実装後、他のアクションとインターリーブされます。
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement tasks from an OpenSpec change (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `OpenSpec の変更からタスクを実装します。

${STORE_SELECTION_GUIDANCE}

**入力**: 必要に応じて、変更名を指定します (例: \`/opsx:apply add-auth\`)。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更を選択**

名前が指定されている場合は、それを使用します。さもないと：
- ユーザーが変更について言及したかどうかを会話のコンテキストから推測します
- アクティブな変更が 1 つだけ存在する場合は自動選択
- 曖昧な場合は、\`openspec list --json\` を実行して利用可能な変更を取得し、**AskUserQuestion ツール**を使用してユーザーに選択させます。

常に「変​​更の使用: <name>」と上書き方法 (例: \`/opsx:apply <other>\`) をアナウンスします。

2. **ステータスを確認してスキーマを理解します**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
JSON を解析して以下を理解します。
- \`schemaName\`: 使用されているワークフロー (例: 「仕様主導」)
- \`planningHome\`、\`changeRoot\`、および \`actionContext\`: 計画範囲と編集制約
- どのアーティファクトにタスクが含まれているか (通常、仕様主導型の場合は「タスク」、その他の場合はステータスを確認)

3. **適用手順を取得**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

これは以下を返します:
- \`contextFiles\`: アーティファクト ID -> 具体的なファイル パスの配列 (スキーマによって異なります)
- 進行状況 (合計、完了、残り)
- ステータス付きタスクリスト
- 現在の状態に基づいた動的な命令

**ハンドル状態:**
- \`state: "blocked"\` (アーティファクトが欠落している) の場合: メッセージを表示し、\`/opsx:continue\` の使用を提案します。
- \`state: "all_done"\` の場合: おめでとうございます、アーカイブを提案してください
- それ以外の場合: 実装に進みます。

4. **コンテキスト ファイルの読み取り**

適用命令の出力から、\`contextFiles\` の下にリストされているすべてのファイル パスを読み取ります。
ファイルは使用されているスキーマによって異なります。
- **仕様主導**: 提案、仕様、設計、タスク
- その他のスキーマ: CLI 出力の contextFiles に従います。

5. **現在の進行状況を表示**

画面：
- 使用されているスキーマ
- 進行状況: 「N/M 個のタスクが完了しました」
- 残りのタスクの概要
- CLIからの動的指示

6. **タスクを実装します (完了またはブロックされるまでループします)**

保留中のタスクごとに次のようにします。
- どのタスクが進行中かを表示します
- 必要なコード変更を行う
- 変更を最小限に抑え、焦点を絞ったものにします
- タスク ファイルでタスクを完了としてマークします: \`- [ ]\` → \`- [x]\`
- 次のタスクに進む

**次の場合は一時停止します**
- タスクが不明瞭 → 説明を求める
- 実装により設計上の問題が明らかになった → アーティファクトの更新を提案
- エラーまたはブロッカーが発生しました → 報告してガイダンスを待ちます
- ユーザーによる割り込み

7. **完了または一時停止時にステータスを表示**

画面：
- このセッションでタスクが完了しました
- 全体的な進捗状況: 「N/M 個のタスクが完了しました」
- すべて完了したら: アーカイブを提案します
- 一時停止した場合: 理由を説明し、指示を待ちます

**実装時の出力**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**完了時の出力**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! You can archive this change with \`/opsx:archive\`.
\`\`\`

**一時停止時の出力 (問題が発生しました)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**ガードレール**
- 完了するかブロックされるまでタスクを実行し続けます
- 開始する前に必ずコンテキスト ファイルを読み取ります (適用命令の出力から)。
- タスクがあいまいな場合は、実行する前に一時停止して質問してください
- 実装で問題が明らかになった場合は、一時停止してアーティファクトの更新を提案します
- コードの変更を最小限に抑え、各タスクの範囲に限定します
- 各タスクが完了したらすぐに「タスクを更新」チェックボックスをオンにします
- エラー、阻害要因、または不明瞭な要件がある場合は一時停止します - 推測しないでください
- CLI 出力から contextFiles を使用し、特定のファイル名を想定しないでください。

**流動的なワークフローの統合**

このスキルは、「変更に対するアクション」モデルをサポートします。

- **いつでも呼び出すことができます**: すべてのアーティファクトが完了する前 (タスクが存在する場合)、部分的な実装後、他のアクションとインターリーブされます。
- **アーティファクトの更新を許可**: 実装により設計上の問題が明らかになった場合は、アーティファクトの更新を提案します - フェーズロックではなく、流動的に作業します`
  };
}
