/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: '実験的ワークフローで完了した変更をアーカイブします。実装完了後に変更を確定してアーカイブしたいときに使用します。',
    instructions: `実験的ワークフローで完了した変更をアーカイブします。

${STORE_SELECTION_GUIDANCE}

**入力**: 必要に応じて、変更名を指定します。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and ask the user to select one

   When prompting, show only active changes (not already archived).
   Include the schema used for each change if available.

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:archive <other>\`).

   **Load current archive inputs before the existing archive checks:**

   After resolving the selected change and planning root, run:
   \`\`\`bash
   openspec instructions archive --change "<name>" --json
   \`\`\`
   Keep the same selected-root flags on this command. This lookup is advisory and
   optional: it only supplies extra prompt inputs, so it must never block archiving.
   If it exits non-zero or returns invalid JSON — for example on an older CLI that
   does not support this command yet — continue the archive workflow with no
   context and no operation guidance. Do not report an error and do not stop.

   A successful response may omit both optional fields. Treat \`context\` as a
   required prompt-level input: read and consider it, and apply relevant project
   facts, conventions, and constraints. Treat \`operationGuidance\` as optional
   additive advice: read and consider every entry, and follow entries that are
   applicable and compatible with the built-in archive workflow.

   Keep both fields separate from built-in steps, explicit user choices, resolved
   paths, CLI checks, and command contracts. If context conflicts with one of those
   controlling inputs, report the conflict and preserve the controlling value. If
   guidance is inapplicable or conflicts with a controlling input, do not follow it
   and explain why. Do not infer replacement paths, skipped prompts, or flags from
   either field, and do not copy their text verbatim into specs, change artifacts,
   or archive summaries unless the user separately asks for it. These are
   prompt-level behavior contracts, not enforceable checks.

2. **アーティファクトの完了ステータスを確認します**

\`openspec status --change "<name>" --json\` を実行して、アーティファクトの完了を確認します。

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\`, \`skipped\`, or other)

   **If any artifacts are neither \`done\` nor \`skipped\`** (skipped artifacts satisfy the requirement - the change declares skip_specs):
   - Display warning listing incomplete artifacts
   - Ask the user to confirm they want to proceed
   - Proceed if user confirms

3. **タスクの完了ステータスを確認します**

タスク ファイル (通常は \`tasks.md\`) を読んで、不完全なタスクがないか確認します。

\`- [ ]\` (未完了) と \`- [x]\` (完了) でマークされたタスクを数えます。

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Ask the user to confirm they want to proceed
   - Proceed if user confirms

**タスク ファイルが存在しない場合:** タスク関連の警告なしで続行します。

4. **デルタ仕様の同期状態を評価します**

   Use \`artifactPaths.specs.existingOutputPaths\` from status JSON as the only
   delta-spec source. If the \`specs\` entry is missing or
   \`existingOutputPaths\` is empty, proceed without a sync prompt and do not infer
   delta specs from other artifacts.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` (use the store-aware \`planningHome.root\` from step 2, not a hardcoded repo path)
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

**プロンプトオプション:**
- 変更が必要な場合: 「今すぐ同期 (推奨)」、「同期せずにアーカイブ」
- すでに同期されている場合: 「今すぐアーカイブ」、「とにかく同期」、「キャンセル」

   Route on the answer:
   - "Cancel" — stop, do not archive
   - "Archive without syncing" or "Archive now" — proceed to archive
   - "Sync now" or "Sync anyway" — sync, then verify (below)
   - Anything else — ask again rather than archiving

   Before a selected sync writes any main spec, run
   \`openspec instructions specs --change "<name>" --json\` once with the same
   selected-root flags. Require a zero exit status and valid artifact-instruction
   JSON. If the lookup fails or returns invalid JSON, report the error and stop
   before writing any main spec or moving the change. A valid response with omitted
   \`rules\` is the no-rules case. Apply returned \`rules\` only to the content and
   form of main specs produced by this merge; do not use them as archive guidance,
   change CLI behavior, or copy the rule text into any output file.

   Then run the \`openspec-sync-specs\` workflow inline (agent-driven intelligent merge) for change '<name>', passing the delta spec analysis and the fetched specs-rule snapshot from above, and wait for it to finish. The inline sync must reuse that snapshot without fetching \`specs\` instructions again. Do not delegate it to a background task — step 5 would move \`changeRoot\` out from under a sync that is still reading it, leaving the change archived and the main specs never updated. If your agent can only run it by delegation, delegate synchronously and wait for the result.

   Then re-run the comparison from the top of this step against every capability that has a delta spec in \`artifactPaths.specs.existingOutputPaths\` — not only the ones the sync reports it touched. A successful sync leaves nothing left to apply, so each capability must now read as already synced:
   - ADDED requirements present
   - MODIFIED requirements carrying the scenario and description changes named in the delta, with their other scenarios intact
   - REMOVED requirements gone
   - RENAMED requirements present under the new name and absent under the old one

   If the sync failed, or any capability does not match, report what differs and stop — do not archive. Nothing has moved and \`changeRoot\` is intact, so the user can fix the mismatch or re-run the sync and start the archive again.

5. **アーカイブを実行します**

\`archive\` ディレクトリが存在しない場合は、\`planningHome.changesDir\` の下に作成します。
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate the target name: use the change name as-is when it already starts with a \`YYYY-MM-DD-\` prefix; otherwise prepend the current date as \`YYYY-MM-DD-<change-name>\`. Never stack a second date (same rule as \`openspec archive\`).

**ターゲットが既に存在するかどうかを確認します:**
- 「はい」の場合: エラーで失敗します。既存のアーカイブの名前を変更するか、別の日付を使用することを提案します。
- 「いいえ」の場合: \`changeRoot\` をアーカイブ ディレクトリに移動します。

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
   \`\`\`

6. **概要を表示**

以下を含むアーカイブ完了の概要を表示します。
- 名前の変更
- 使用されたスキーマ
- アーカイブの場所
- 仕様が同期されたかどうか (該当する場合)
- 警告に関するメモ (不完全な成果物/タスク)

**成功時の出力**

\`\`\`markdown
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/<target-name>/
**Specs:** <"✓ Synced to main specs" only if the step 4 verification passed; otherwise "No delta specs" or "Sync skipped">

<"All artifacts complete. All tasks complete." — or, if archived with warnings, list them instead (e.g. "Archived with 2 incomplete tasks")>
\`\`\`

**Guardrails**
- Announce the selected change; prompt for selection when it is ambiguous
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, run the \`openspec-sync-specs\` workflow inline (agent-driven)
- Never archive while a spec sync is still in flight — run the sync inline and verify the main specs before moving \`changeRoot\`
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- Apply relevant runtime context and report conflicts; operation guidance remains advisory
- Consider every guidance entry and explain any inapplicable or conflicting advice
- Existing CLI checks, resolved paths, prompts, and command contracts are unchanged
- Artifact rules constrain only the specs being written and are never operation guidance
- Never copy runtime context, operation guidance, or artifact-rule text verbatim into output files`,
    license: 'MIT',
    compatibility: 'OpenSpec CLI が必要です。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: '実験的ワークフローで完了した変更をアーカイブする',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `実験的ワークフローで完了した変更をアーカイブします。

${STORE_SELECTION_GUIDANCE}

**入力**: オプションで、\`/opsx:archive\` の後に変更名を指定します (例: \`/opsx:archive add-auth\`)。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and ask the user to select one

   When prompting, show only active changes (not already archived).
   Include the schema used for each change if available.

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:archive <other>\`).

   **Load current archive inputs before the existing archive checks:**

   After resolving the selected change and planning root, run:
   \`\`\`bash
   openspec instructions archive --change "<name>" --json
   \`\`\`
   Keep the same selected-root flags on this command. This lookup is advisory and
   optional: it only supplies extra prompt inputs, so it must never block archiving.
   If it exits non-zero or returns invalid JSON — for example on an older CLI that
   does not support this command yet — continue the archive workflow with no
   context and no operation guidance. Do not report an error and do not stop.

   A successful response may omit both optional fields. Treat \`context\` as a
   required prompt-level input: read and consider it, and apply relevant project
   facts, conventions, and constraints. Treat \`operationGuidance\` as optional
   additive advice: read and consider every entry, and follow entries that are
   applicable and compatible with the built-in archive workflow.

   Keep both fields separate from built-in steps, explicit user choices, resolved
   paths, CLI checks, and command contracts. If context conflicts with one of those
   controlling inputs, report the conflict and preserve the controlling value. If
   guidance is inapplicable or conflicts with a controlling input, do not follow it
   and explain why. Do not infer replacement paths, skipped prompts, or flags from
   either field, and do not copy their text verbatim into specs, change artifacts,
   or archive summaries unless the user separately asks for it. These are
   prompt-level behavior contracts, not enforceable checks.

2. **アーティファクトの完了ステータスを確認します**

\`openspec status --change "<name>" --json\` を実行して、アーティファクトの完了を確認します。

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\`, \`skipped\`, or other)

   **If any artifacts are neither \`done\` nor \`skipped\`** (skipped artifacts satisfy the requirement - the change declares skip_specs):
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **タスクの完了ステータスを確認します**

タスク ファイル (通常は \`tasks.md\`) を読んで、不完全なタスクがないか確認します。

\`- [ ]\` (未完了) と \`- [x]\` (完了) でマークされたタスクを数えます。

**不完全なタスクが見つかった場合:**
- 未完了のタスクの数を示す警告を表示します
- 続行するにはユーザーに確認を求めるプロンプトを表示します
- ユーザーが確認したら続行します

**タスク ファイルが存在しない場合:** タスク関連の警告なしで続行します。

4. **デルタ仕様の同期状態を評価します**

   Use \`artifactPaths.specs.existingOutputPaths\` from status JSON as the only
   delta-spec source. If the \`specs\` entry is missing or
   \`existingOutputPaths\` is empty, proceed without a sync prompt and do not infer
   delta specs from other artifacts.

   **If delta specs exist:**
   - Compare each delta spec with its corresponding main spec at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` (use the store-aware \`planningHome.root\` from step 2, not a hardcoded repo path)
   - Determine what changes would be applied (adds, modifications, removals, renames)
   - Show a combined summary before prompting

**プロンプトオプション:**
- 変更が必要な場合: 「今すぐ同期 (推奨)」、「同期せずにアーカイブ」
- すでに同期されている場合: 「今すぐアーカイブ」、「とにかく同期」、「キャンセル」

   Route on the answer:
   - "Cancel" — stop, do not archive
   - "Archive without syncing" or "Archive now" — proceed to archive
   - "Sync now" or "Sync anyway" — sync, then verify (below)
   - Anything else — ask again rather than archiving

   Before a selected sync writes any main spec, run
   \`openspec instructions specs --change "<name>" --json\` once with the same
   selected-root flags. Require a zero exit status and valid artifact-instruction
   JSON. If the lookup fails or returns invalid JSON, report the error and stop
   before writing any main spec or moving the change. A valid response with omitted
   \`rules\` is the no-rules case. Apply returned \`rules\` only to the content and
   form of main specs produced by this merge; do not use them as archive guidance,
   change CLI behavior, or copy the rule text into any output file.

   Then run the \`/opsx:sync\` workflow inline (agent-driven intelligent merge) for change '<name>', passing the delta spec analysis and the fetched specs-rule snapshot from above, and wait for it to finish. The inline sync must reuse that snapshot without fetching \`specs\` instructions again. Do not delegate it to a background task — step 5 would move \`changeRoot\` out from under a sync that is still reading it, leaving the change archived and the main specs never updated. If your agent can only run it by delegation, delegate synchronously and wait for the result.

   Then re-run the comparison from the top of this step against every capability that has a delta spec in \`artifactPaths.specs.existingOutputPaths\` — not only the ones the sync reports it touched. A successful sync leaves nothing left to apply, so each capability must now read as already synced:
   - ADDED requirements present
   - MODIFIED requirements carrying the scenario and description changes named in the delta, with their other scenarios intact
   - REMOVED requirements gone
   - RENAMED requirements present under the new name and absent under the old one

   If the sync failed, or any capability does not match, report what differs and stop — do not archive. Nothing has moved and \`changeRoot\` is intact, so the user can fix the mismatch or re-run the sync and start the archive again.

5. **アーカイブを実行します**

\`archive\` ディレクトリが存在しない場合は、\`planningHome.changesDir\` の下に作成します。
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

   Generate the target name: use the change name as-is when it already starts with a \`YYYY-MM-DD-\` prefix; otherwise prepend the current date as \`YYYY-MM-DD-<change-name>\`. Never stack a second date (same rule as \`openspec archive\`).

**ターゲットが既に存在するかどうかを確認します:**
- 「はい」の場合: エラーで失敗します。既存のアーカイブの名前を変更するか、別の日付を使用することを提案します。
- 「いいえ」の場合: \`changeRoot\` をアーカイブ ディレクトリに移動します。

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
   \`\`\`

6. **概要を表示**

以下を含むアーカイブ完了の概要を表示します。
- 名前の変更
- 使用されたスキーマ
- アーカイブの場所
- 仕様の同期ステータス (同期済み / 同期スキップ / デルタ仕様なし)
- 警告に関するメモ (不完全な成果物/タスク)

**成功時の出力**

\`\`\`markdown
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/<target-name>/
**Specs:** ✓ Synced to main specs

すべてのアーティファクトが完了しています。すべてのタスクが完了しています。
\`\`\`

**成功時の出力 (デルタ仕様なし)**

\`\`\`markdown
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/<target-name>/
**Specs:** No delta specs

すべてのアーティファクトが完了しています。すべてのタスクが完了しています。
\`\`\`

**成功時の出力と警告**

\`\`\`markdown
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/<target-name>/
**Specs:** Sync skipped (user chose to skip)

**警告:**
- 未完了アーティファクト 2 件を含めてアーカイブしました
- 未完了タスク 3 件を含めてアーカイブしました
- delta spec 同期をスキップしました（ユーザーがスキップを選択）

意図した結果でない場合はアーカイブを確認してください。
\`\`\`

**エラー時の出力 (アーカイブが存在する)**

\`\`\`markdown
## Archive Failed

**Change:** <change-name>
**Target:** the archive path derived from \`planningHome.changesDir\`/<target-name>/

対象のアーカイブディレクトリは既に存在します。

**選択肢:**
1. 既存のアーカイブ名を変更する
2. 重複であれば既存のアーカイブを削除する
3. 別の日付になるまで待ってアーカイブする
\`\`\`

**Guardrails**
- Announce the selected change; prompt for selection when it is ambiguous
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- If sync is requested, run the \`/opsx:sync\` workflow inline (agent-driven)
- Never archive while a spec sync is still in flight — run the sync inline and verify the main specs before moving \`changeRoot\`
- If delta specs exist, always run the sync assessment and show the combined summary before prompting
- Apply relevant runtime context and report conflicts; operation guidance remains advisory
- Consider every guidance entry and explain any inapplicable or conflicting advice
- Existing CLI checks, resolved paths, prompts, and command contracts are unchanged
- Artifact rules constrain only the specs being written and are never operation guidance
- Never copy runtime context, operation guidance, or artifact-rule text verbatim into output files`
  };
}
