/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: `実験的ワークフローで完了した変更をアーカイブします。

${STORE_SELECTION_GUIDANCE}

**入力**: 必要に応じて、変更名を指定します。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更名が指定されていない場合は、選択を求めるプロンプトが表示されます**

\`openspec list --json\` を実行して、利用可能な変更を取得します。 **AskUserQuestion ツール**を使用して、ユーザーに選択させます。

アクティブな変更 (まだアーカイブされていない) のみを表示します。
可能な場合は、各変更に使用されたスキーマを含めます。

**重要**: 変更を推測したり自動選択したりしないでください。常にユーザーに選択してもらいます。

2. **アーティファクトの完了ステータスを確認します**

\`openspec status --change "<name>" --json\` を実行して、アーティファクトの完了を確認します。

JSON を解析して以下を理解します。
- \`schemaName\`: 使用されているワークフロー
- \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、および \`actionContext\`: パス​​とスコープのコンテキスト
- \`artifacts\`: アーティファクトとそのステータスのリスト (\`done\` またはその他)

**いずれかのアーティファクトが \`done\` ではない場合:**
- 不完全なアーティファクトをリストした警告を表示します
- **AskUserQuestion ツール**を使用して、ユーザーが続行を希望していることを確認します
- ユーザーが確認したら続行します

3. **タスクの完了ステータスを確認します**

タスク ファイル (通常は \`tasks.md\`) を読んで、不完全なタスクがないか確認します。

\`- [ ]\` (未完了) と \`- [x]\` (完了) でマークされたタスクを数えます。

**不完全なタスクが見つかった場合:**
- 未完了のタスクの数を示す警告を表示します
- **AskUserQuestion ツール**を使用して、ユーザーが続行を希望していることを確認します
- ユーザーが確認したら続行します

**タスク ファイルが存在しない場合:** タスク関連の警告なしで続行します。

4. **デルタ仕様の同期状態を評価します**

ステータス JSON から \`artifactPaths.specs.existingOutputPaths\` を使用して、デルタ仕様を確認します。存在しない場合は、同期プロンプトを表示せずに続行します。

**デルタ仕様が存在する場合:**
- 各デルタ仕様を \`openspec/specs/<capability>/spec.md\` で対応するメイン仕様と比較します。
- どのような変更が適用されるかを決定します (追加、変更、削除、名前変更)。
- プロンプトの前に結合された概要を表示する

**プロンプトオプション:**
- 変更が必要な場合: 「今すぐ同期 (推奨)」、「同期せずにアーカイブ」
- すでに同期されている場合: 「今すぐアーカイブ」、「とにかく同期」、「キャンセル」

ユーザーが同期を選択した場合は、タスク ツールを使用します (subagent_type: 「汎用」、プロンプト: 「スキル ツールを使用して、'<name>' を変更するために openspec-sync-specs を呼び出します。デルタ仕様分析: <分析されたデルタ仕様の概要を含める>」)。選択に関係なくアーカイブに進みます。

5. **アーカイブを実行します**

\`archive\` ディレクトリが存在しない場合は、\`planningHome.changesDir\` の下に作成します。
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

現在の日付を使用してターゲット名を生成します: \`YYYY-MM-DD-<change-name>\`

**ターゲットが既に存在するかどうかを確認します:**
- 「はい」の場合: エラーで失敗します。既存のアーカイブの名前を変更するか、別の日付を使用することを提案します。
- 「いいえ」の場合: \`changeRoot\` をアーカイブ ディレクトリに移動します。

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **概要を表示**

以下を含むアーカイブ完了の概要を表示します。
- 名前の変更
- 使用されたスキーマ
- アーカイブの場所
- 仕様が同期されたかどうか (該当する場合)
- 警告に関するメモ (不完全な成果物/タスク)

**成功時の出力**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs (or "No delta specs" or "Sync skipped")

All artifacts complete. All tasks complete.
\`\`\`

**ガードレール**
- 指定されていない場合は、常に変更の選択を求めるプロンプトが表示されます
- 完了チェックにアーティファクト グラフ (openspec status --json) を使用する
- 警告時にアーカイブをブロックしないでください - 通知して確認するだけです
- アーカイブに移動するときに .openspec.yaml を保持します (ディレクトリと一緒に移動します)。
- 何が起こったのかを明確に要約する
- 同期が要求された場合は、openspec-sync-specs アプローチを使用します (エージェント主導)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `実験的ワークフローで完了した変更をアーカイブします。

${STORE_SELECTION_GUIDANCE}

**入力**: オプションで、\`/opsx:archive\` の後に変更名を指定します (例: \`/opsx:archive add-auth\`)。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更名が指定されていない場合は、選択を求めるプロンプトが表示されます**

\`openspec list --json\` を実行して、利用可能な変更を取得します。 **AskUserQuestion ツール**を使用して、ユーザーに選択させます。

アクティブな変更 (まだアーカイブされていない) のみを表示します。
可能な場合は、各変更に使用されたスキーマを含めます。

**重要**: 変更を推測したり自動選択したりしないでください。常にユーザーに選択してもらいます。

2. **アーティファクトの完了ステータスを確認します**

\`openspec status --change "<name>" --json\` を実行して、アーティファクトの完了を確認します。

JSON を解析して以下を理解します。
- \`schemaName\`: 使用されているワークフロー
- \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、および \`actionContext\`: パス​​とスコープのコンテキスト
- \`artifacts\`: アーティファクトとそのステータスのリスト (\`done\` またはその他)

**いずれかのアーティファクトが \`done\` ではない場合:**
- 不完全なアーティファクトをリストした警告を表示します
- 続行するにはユーザーに確認を求めるプロンプトを表示します
- ユーザーが確認したら続行します

3. **タスクの完了ステータスを確認します**

タスク ファイル (通常は \`tasks.md\`) を読んで、不完全なタスクがないか確認します。

\`- [ ]\` (未完了) と \`- [x]\` (完了) でマークされたタスクを数えます。

**不完全なタスクが見つかった場合:**
- 未完了のタスクの数を示す警告を表示します
- 続行するにはユーザーに確認を求めるプロンプトを表示します
- ユーザーが確認したら続行します

**タスク ファイルが存在しない場合:** タスク関連の警告なしで続行します。

4. **デルタ仕様の同期状態を評価します**

ステータス JSON から \`artifactPaths.specs.existingOutputPaths\` を使用して、デルタ仕様を確認します。存在しない場合は、同期プロンプトを表示せずに続行します。

**デルタ仕様が存在する場合:**
- 各デルタ仕様を \`openspec/specs/<capability>/spec.md\` で対応するメイン仕様と比較します。
- どのような変更が適用されるかを決定します (追加、変更、削除、名前変更)。
- プロンプトの前に結合された概要を表示する

**プロンプトオプション:**
- 変更が必要な場合: 「今すぐ同期 (推奨)」、「同期せずにアーカイブ」
- すでに同期されている場合: 「今すぐアーカイブ」、「とにかく同期」、「キャンセル」

ユーザーが同期を選択した場合は、タスク ツールを使用します (subagent_type: 「汎用」、プロンプト: 「スキル ツールを使用して、'<name>' を変更するために openspec-sync-specs を呼び出します。デルタ仕様分析: <分析されたデルタ仕様の概要を含める>」)。選択に関係なくアーカイブに進みます。

5. **アーカイブを実行します**

\`archive\` ディレクトリが存在しない場合は、\`planningHome.changesDir\` の下に作成します。
   \`\`\`bash
   mkdir -p "<planningHome.changesDir>/archive"
   \`\`\`

現在の日付を使用してターゲット名を生成します: \`YYYY-MM-DD-<change-name>\`

**ターゲットが既に存在するかどうかを確認します:**
- 「はい」の場合: エラーで失敗します。既存のアーカイブの名前を変更するか、別の日付を使用することを提案します。
- 「いいえ」の場合: \`changeRoot\` をアーカイブ ディレクトリに移動します。

   \`\`\`bash
   mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
   \`\`\`

6. **概要を表示**

以下を含むアーカイブ完了の概要を表示します。
- 名前の変更
- 使用されたスキーマ
- アーカイブの場所
- 仕様の同期ステータス (同期済み / 同期スキップ / デルタ仕様なし)
- 警告に関するメモ (不完全な成果物/タスク)

**成功時の出力**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs

All artifacts complete. All tasks complete.
\`\`\`

**成功時の出力 (デルタ仕様なし)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** No delta specs

All artifacts complete. All tasks complete.
\`\`\`

**成功時の出力と警告**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** Sync skipped (user chose to skip)

**Warnings:**
- Archived with 2 incomplete artifacts
- Archived with 3 incomplete tasks
- Delta spec sync was skipped (user chose to skip)

Review the archive if this was not intentional.
\`\`\`

**エラー時の出力 (アーカイブが存在する)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Target:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/

Target archive directory already exists.

**Options:**
1. Rename the existing archive
2. Delete the existing archive if it's a duplicate
3. Wait until a different date to archive
\`\`\`

**ガードレール**
- 指定されていない場合は、常に変更の選択を求めるプロンプトが表示されます
- 完了チェックにアーティファクト グラフ (openspec status --json) を使用する
- 警告時にアーカイブをブロックしないでください - 通知して確認するだけです
- アーカイブに移動するときに .openspec.yaml を保持します (ディレクトリと一緒に移動します)。
- 何が起こったのかを明確に要約する
- 同期が要求された場合は、スキル ツールを使用して \`openspec-sync-specs\` を呼び出します (エージェント主導)
- If delta specs exist, always run the sync assessment and show the combined summary before prompting`
  };
}
