/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getBulkArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-bulk-archive-change',
    description: '複数の完了済み変更を一括でアーカイブします。並行して進めた複数の変更をまとめてアーカイブするときに使用します。',
    instructions: `複数の完了済み変更を1回の操作でアーカイブします。

このスキルでは、複数の変更を一括アーカイブできます。仕様の競合は、コードベースを確認して実際に実装済みの内容を判断しながら扱います。

${STORE_SELECTION_GUIDANCE}

**入力**: 不要（選択を促します）

**手順**

1. **進行中の変更を取得**

   \`openspec list --json\` を実行して、進行中の変更をすべて取得します。

   進行中の変更がない場合は、ユーザーに伝えて停止します。

2. **変更選択を促す**

   Ask the user to choose changes (multi-select):
   - Show each change with its schema
   - Include an option for "All changes"
   - Allow any number of selections (1+ works, 2+ is the typical use case)

   **重要**: 自動選択しないでください。必ずユーザーに選ばせます。

   **Load current archive inputs once for the selected root before batch validation:**

   Choose one selected change from this root and run
   \`openspec instructions archive --change "<selected-change>" --json\` with the
   same selected-root flags. This lookup is advisory and optional: it only supplies
   extra prompt inputs, so it must never block the batch. If it fails or returns
   invalid JSON — for example on an older CLI that does not support this command
   yet — continue the batch with no context and no operation guidance. Do not
   report an error and do not stop.

   A valid response may omit \`context\` and \`operationGuidance\`. Treat
   \`context\` as a required prompt-level input across the batch: read and consider
   it, and apply relevant project facts, conventions, and constraints. Treat
   \`operationGuidance\` as optional additive advice: read and consider every
   entry, and follow entries that are applicable and compatible with the built-in
   batch workflow.

   Keep both fields separate from conflict analysis, explicit user choices,
   resolved paths, CLI checks, and command contracts. If context conflicts with one
   of those controlling inputs, report the conflict and preserve the controlling
   value. If guidance is inapplicable or conflicts with a controlling input, do not
   follow it and explain why. Do not infer skipped prompts, replacement paths, or
   flags from either field, and do not copy their text verbatim into specs, changes,
   or summaries. These are prompt-level behavior contracts, not enforceable checks.

3. **Batch validation - gather status for all selected changes**

   選択された各変更について、次を収集します:

   a. **アーティファクト状態** - \`openspec status --change "<name>" --json\` を実行
      - \`schemaName\`, \`artifacts\`, \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, \`actionContext\` を解析
      - どのアーティファクトが \`done\` で、どれが他の状態かを記録

   b. **タスク完了状況** - status JSON から \`artifactPaths.tasks.existingOutputPaths\` を読み取る
      - \`- [ ]\`（未完了）と \`- [x]\`（完了）を数える
      - タスクファイルがない場合は "タスクなし" と記録

   c. **Delta specs** - Check \`artifactPaths.specs.existingOutputPaths\` from status JSON
      - List which capability specs exist
      - For each, extract requirement names (lines matching \`### Requirement: <name>\`)
      - Treat this list as the only delta-spec source. If the \`specs\` entry is
        missing or the list is empty, perform no spec sync or specs-instruction
        lookup for that change; do not infer deltas from unrelated artifacts.
      - Evaluate this independently for every change, including mixed-schema
        batches where some schemas have no \`specs\` artifact.
4. **Detect spec conflicts**

   \`capability -> [それを変更する変更]\` のマップを作ります:

   \`\`\`text
   auth -> [change-a, change-b]  <- CONFLICT (2+ changes)
   api  -> [change-c]            <- OK (only 1 change)
   \`\`\`

   選択された変更のうち2件以上が同じ capability の差分仕様を持つ場合、競合があります。

5. **エージェント的に競合を解決**

   **各競合**について、コードベースを調査します:

   a. 競合する各変更の**差分仕様を読み**、それぞれが何を追加/変更すると主張しているか理解する

   b. 実装の根拠を得るために**コードベースを検索**:
      - 各差分仕様の要件を実装するコードを探す
      - 関連ファイル、関数、テストを確認

   c. **解決方法を決定**:
      - 実装済みが1件だけの場合 -> その変更の仕様を同期
      - 両方実装済みの場合 -> 時系列順で適用（古いものを先、新しいものが上書き）
      - どちらも未実装の場合 -> 仕様同期をスキップし、ユーザーに警告

   d. **Record resolution** for each conflict:
      - An inclusion or exclusion decision for every delta spec, keyed by change and capability
      - Which included delta specs to apply and in what order
      - Which delta specs to exclude from sync because their implementation is missing
      - Rationale (what was found in codebase)

6. **統合ステータス表を表示**

   すべての変更を要約する表を表示します:

   \`\`\`markdown
   | Change              | Artifacts | Tasks | Specs   | Conflicts | Status |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完了      | 5/5   | 2差分   | なし      | 準備完了 |
   | project-config      | 完了      | 3/3   | 1差分   | なし      | 準備完了 |
   | add-oauth           | 完了      | 4/4   | 1差分   | auth (!)  | 準備完了* |
   | add-verify-skill    | 残り1件   | 2/5   | なし    | なし      | 警告   |
   \`\`\`

   For conflicts, show the resolution:
   \`\`\`text
   * Conflict resolution:
     - auth spec: Will apply add-oauth then add-jwt (both implemented, chronological order)
   \`\`\`

   For incomplete changes, show warnings:
   \`\`\`text
   Warnings:
   - add-verify-skill: 1 incomplete artifact, 3 incomplete tasks
   \`\`\`

7. **一括操作の確認**

   Ask the user a single confirmation question:

   - "N 件の変更をアーカイブしますか？" をステータスに応じて提示
   - 選択肢の例:
     - "N 件すべてをアーカイブ"
     - "準備完了の N 件のみアーカイブ（未完了は除外）"
     - "キャンセル"

   未完了がある場合は、警告付きでアーカイブされることを明記。

   Route on the answer by intent, not by exact label — you wrote these labels,
   so match what the user picked rather than the wording above:
   - "Cancel" — stop, do not archive. Report that nothing was archived and skip the remaining steps.
   - The archive-everything option — proceed with every selected change
   - The ready-only option — proceed with only the changes the step 6 table marks \`Ready\` or \`Ready*\`, and record the rest as Skipped in step 8d. If a \`Ready*\` change's conflict partner is skipped, re-derive that conflict's resolution using only the changes being archived.
   - Anything else — ask again rather than archiving

   Before step 8 writes the first main spec or moves any change, fetch every
   required specs-rule snapshot for the confirmed batch. For each change that will
   sync concrete \`artifactPaths.specs.existingOutputPaths\`, run
   \`openspec instructions specs --change "<name>" --json\` exactly once with the
   same selected-root flags. Obtain all snapshots before the first write or move.
   If any lookup exits non-zero or returns invalid artifact-instruction JSON,
   identify the affected change, report the error, and stop the whole batch before
   any main-spec write or change move. Do not treat lookup failure as omitted
   rules. A valid response without \`rules\` is the no-rules case.

8. **Execute archive for each confirmed change**

   Before processing, carry the recorded decisions from step 5 (after any step 7 re-derivation) into two per-delta sets:
   - \`includedDeltas\`: all non-conflicting delta specs from confirmed changes plus conflict deltas selected for sync
   - \`excludedDeltas\`: conflict deltas from confirmed changes excluded because their implementation is missing
   - A single change can have both included and excluded delta specs. Keep the decision per delta; do not collapse it into a per-change sync flag.

   Process changes in the determined order (respecting conflict resolution):

   a. **Sync included delta specs**:
      - Run the \`openspec-sync-specs\` workflow inline (agent-driven intelligent merge) only for changes with entries in \`includedDeltas\`, passing only the included delta paths and explicitly instructing it to ignore that change's \`excludedDeltas\`. Wait for it to finish.
      - For conflicts, apply in resolved order.
      - Pass that change's fetched specs-rule snapshot into inline sync; inline
        sync must reuse it without fetching instructions again
      - Apply artifact rules only to main specs produced by that change. They do
        not change conflict resolution, archive behavior, or CLI contracts, and
        their text is not copied into an output file
      - Do not delegate to a background task — step 8c would move \`changeRoot\` out from under a sync that is still reading it.
      - If a change has no included delta specs, do not run the sync workflow for it.

   b. **Verify included delta specs before moving changeRoot**:
      - Re-run the comparison only for delta specs in \`includedDeltas\` against main spec at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` (use the store-aware \`planningHome.root\` from step 3 status JSON, not a hardcoded repo path).
      - Verify that main specs are updated:
        - ADDED requirements present
        - MODIFIED requirements carrying scenario and description changes named in the delta, with their other scenarios intact
        - REMOVED requirements gone
        - RENAMED requirements present under the new name and absent under the old one
      - Do not verify delta specs in \`excludedDeltas\`; they are intentionally left unsynced.
      - If sync failed or any capability does not match verification, report what differs and fail/skip moving that change's \`changeRoot\` — do not archive that change. \`changeRoot\` remains intact.

   c. **Perform the archive**:

      Target name: use the change name as-is when it already starts with a \`YYYY-MM-DD-\` prefix; otherwise prepend the current date as \`YYYY-MM-DD-<name>\` (same rule as \`openspec archive\`).

      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
      \`\`\`

   d. **Track outcome** for each change:
      - Success: archived successfully
      - Failed: error during archive or spec verification (record error)
      - Skipped: user chose not to archive (if applicable)
      - Sync skipped: for every delta in \`excludedDeltas\`, report \`sync skipped\` with the change, capability, and recorded reason. This is distinct from skipping the archive.

9. **サマリーを表示**

   最終結果を表示:

   \`\`\`markdown
   ## Bulk Archive Complete

   3 件の変更をアーカイブしました:
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   1 件の変更をスキップしました:
   - add-verify-skill（未完了のためユーザーがアーカイブしないことを選択）

   Spec sync summary:
   - 4 delta specs synced to main specs
   - 1 delta spec sync skipped (add-jwt/auth: implementation not found)
   - 1 conflict resolved (auth: synced add-oauth, skipped add-jwt)
   \`\`\`

   If any failures:
   \`\`\`text
   Failed 1 change:
   - some-change: Archive directory already exists
   \`\`\`

**競合解決の例**

Example 1: Only one implemented
\`\`\`text
Conflict: <planningHome.root>/openspec/specs/auth/spec.md touched by [add-oauth, add-jwt]

add-oauth を確認:
- 差分は "OAuth Provider Integration" 要件を追加
- コードベースを検索... OAuth フローを実装する src/auth/oauth.ts を検出

add-jwt を確認:
- 差分は "JWT Token Handling" 要件を追加
- コードベースを検索... JWT 実装は見つからず

解決: add-oauth のみ実装済みです。add-oauth の仕様だけを同期します。
\`\`\`

Example 2: Both implemented
\`\`\`text
Conflict: <planningHome.root>/openspec/specs/api/spec.md touched by [add-rest-api, add-graphql]

add-rest-api を確認（2026-01-10 作成）:
- 差分は "REST Endpoints" 要件を追加
- コードベースを検索... src/api/rest.ts を検出

add-graphql を確認（2026-01-15 作成）:
- 差分は "GraphQL Schema" 要件を追加
- コードベースを検索... src/api/graphql.ts を検出

解決: 両方とも実装済みです。add-rest-api の仕様を先に適用し、
次に add-graphql の仕様を適用します（時系列順。新しいものを優先）。
\`\`\`

**成功時の出力**

\`\`\`markdown
## Bulk Archive Complete

Archived N changes:
- <change-1> -> archive/<target-name-1>/
- <change-2> -> archive/<target-name-2>/

仕様同期サマリー:
- N 件の差分仕様をメイン仕様へ同期
- 競合なし（または: M 件の競合を解決）
\`\`\`

**一部成功時の出力**

\`\`\`markdown
## Bulk Archive Complete (partial)

Archived N changes:
- <change-1> -> archive/<target-name-1>/

M 件の変更をスキップしました:
- <change-2>（未完了のためユーザーがアーカイブしないことを選択）

K 件の変更に失敗しました:
- <change-3>: アーカイブディレクトリが既に存在します
\`\`\`

**変更がない場合の出力**

\`\`\`markdown
## No Changes to Archive

進行中の変更はありません。\`/opsx:new\` で新しい変更を作成してください。
\`\`\`

**Guardrails**
- Allow any number of changes (1+ is fine, 2+ is the typical use case)
- Always prompt for selection, never auto-select
- Detect spec conflicts early and resolve by checking codebase
- When both changes are implemented, apply specs in chronological order
- Skip spec sync only when implementation is missing (warn user)
- Show clear per-change status before confirming
- Use single confirmation for entire batch
- Never archive after the user cancels the confirmation — a cancelled batch archives nothing
- Track and report all outcomes (success/skip/fail)
- Preserve .openspec.yaml when moving to archive
- Archive directory target uses current date: YYYY-MM-DD-<name>; a name that already starts with a \`YYYY-MM-DD-\` prefix is used as-is (never stack a second date)
- If archive target exists, fail that change but continue with others
- If sync is requested, run the \`openspec-sync-specs\` workflow inline (agent-driven) for each change with included delta specs
- Carry the per-delta \`includedDeltas\` and \`excludedDeltas\` decisions into execution; sync and verify only included deltas
- Report every excluded delta as \`sync skipped\` without treating the archive itself as skipped
- Never archive a change while a spec sync is still in flight — run the sync inline and verify main specs at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` before moving \`changeRoot\`
- Fetch archive inputs once per selected root before spec inspection or moves
- Fetch all required specs-rule snapshots before the batch's first main-spec write or move
- A failed archive-inputs lookup never blocks the batch; it proceeds with no context or guidance
- A failed specs instruction lookup stops the whole batch atomically
- Changes without concrete \`artifactPaths.specs.existingOutputPaths\` continue without spec sync
- Apply relevant runtime context across the batch and report conflicts
- Operation guidance remains advisory; consider every entry and explain rejected advice
- Keep runtime inputs, conflict analysis, CLI-derived values, and artifact rules separate
- Artifact rules constrain only written specs
- Never copy runtime input or artifact-rule text verbatim into output files`,
    license: 'MIT',
    compatibility: 'OpenSpec CLI が必要です。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBulkArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bulk Archive',
    description: '複数の完了済み変更を一括でアーカイブする',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental', 'bulk'],
    content: `複数の完了済み変更を1回の操作でアーカイブします。

このスキルでは、複数の変更を一括アーカイブできます。仕様の競合は、コードベースを確認して実際に実装済みの内容を判断しながら扱います。

${STORE_SELECTION_GUIDANCE}

**入力**: 不要（選択を促します）

**手順**

1. **進行中の変更を取得**

   \`openspec list --json\` を実行して、進行中の変更をすべて取得します。

   進行中の変更がない場合は、ユーザーに伝えて停止します。

2. **変更選択を促す**

   Ask the user to choose changes (multi-select):
   - Show each change with its schema
   - Include an option for "All changes"
   - Allow any number of selections (1+ works, 2+ is the typical use case)

   **重要**: 自動選択しないでください。必ずユーザーに選ばせます。

   **Load current archive inputs once for the selected root before batch validation:**

   Choose one selected change from this root and run
   \`openspec instructions archive --change "<selected-change>" --json\` with the
   same selected-root flags. This lookup is advisory and optional: it only supplies
   extra prompt inputs, so it must never block the batch. If it fails or returns
   invalid JSON — for example on an older CLI that does not support this command
   yet — continue the batch with no context and no operation guidance. Do not
   report an error and do not stop.

   A valid response may omit \`context\` and \`operationGuidance\`. Treat
   \`context\` as a required prompt-level input across the batch: read and consider
   it, and apply relevant project facts, conventions, and constraints. Treat
   \`operationGuidance\` as optional additive advice: read and consider every
   entry, and follow entries that are applicable and compatible with the built-in
   batch workflow.

   Keep both fields separate from conflict analysis, explicit user choices,
   resolved paths, CLI checks, and command contracts. If context conflicts with one
   of those controlling inputs, report the conflict and preserve the controlling
   value. If guidance is inapplicable or conflicts with a controlling input, do not
   follow it and explain why. Do not infer skipped prompts, replacement paths, or
   flags from either field, and do not copy their text verbatim into specs, changes,
   or summaries. These are prompt-level behavior contracts, not enforceable checks.

3. **Batch validation - gather status for all selected changes**

   選択された各変更について、次を収集します:

   a. **アーティファクト状態** - \`openspec status --change "<name>" --json\` を実行
      - \`schemaName\`, \`artifacts\`, \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, \`actionContext\` を解析
      - どのアーティファクトが \`done\` で、どれが他の状態かを記録

   b. **タスク完了状況** - status JSON から \`artifactPaths.tasks.existingOutputPaths\` を読み取る
      - \`- [ ]\`（未完了）と \`- [x]\`（完了）を数える
      - タスクファイルがない場合は "タスクなし" と記録

   c. **Delta specs** - Check \`artifactPaths.specs.existingOutputPaths\` from status JSON
      - List which capability specs exist
      - For each, extract requirement names (lines matching \`### Requirement: <name>\`)
      - Treat this list as the only delta-spec source. If the \`specs\` entry is
        missing or the list is empty, perform no spec sync or specs-instruction
        lookup for that change; do not infer deltas from unrelated artifacts.
      - Evaluate this independently for every change, including mixed-schema
        batches where some schemas have no \`specs\` artifact.

4. **仕様の競合を検出**

   \`capability -> [それを変更する変更]\` のマップを作ります:

   \`\`\`text
   auth -> [change-a, change-b]  <- CONFLICT (2+ changes)
   api  -> [change-c]            <- OK (only 1 change)
   \`\`\`

   選択された変更のうち2件以上が同じ capability の差分仕様を持つ場合、競合があります。

5. **エージェント的に競合を解決**

   **各競合**について、コードベースを調査します:

   a. 競合する各変更の**差分仕様を読み**、それぞれが何を追加/変更すると主張しているか理解する

   b. 実装の根拠を得るために**コードベースを検索**:
      - 各差分仕様の要件を実装するコードを探す
      - 関連ファイル、関数、テストを確認

   c. **解決方法を決定**:
      - 実装済みが1件だけの場合 -> その変更の仕様を同期
      - 両方実装済みの場合 -> 時系列順で適用（古いものを先、新しいものが上書き）
      - どちらも未実装の場合 -> 仕様同期をスキップし、ユーザーに警告

   d. **Record resolution** for each conflict:
      - An inclusion or exclusion decision for every delta spec, keyed by change and capability
      - Which included delta specs to apply and in what order
      - Which delta specs to exclude from sync because their implementation is missing
      - Rationale (what was found in codebase)

6. **統合ステータス表を表示**

   すべての変更を要約する表を表示します:

   \`\`\`markdown
   | Change              | Artifacts | Tasks | Specs   | Conflicts | Status |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完了      | 5/5   | 2差分   | なし      | 準備完了 |
   | project-config      | 完了      | 3/3   | 1差分   | なし      | 準備完了 |
   | add-oauth           | 完了      | 4/4   | 1差分   | auth (!)  | 準備完了* |
   | add-verify-skill    | 残り1件   | 2/5   | なし    | なし      | 警告   |
   \`\`\`

   For conflicts, show the resolution:
   \`\`\`text
   * Conflict resolution:
     - auth spec: Will apply add-oauth then add-jwt (both implemented, chronological order)
   \`\`\`

   For incomplete changes, show warnings:
   \`\`\`text
   Warnings:
   - add-verify-skill: 1 incomplete artifact, 3 incomplete tasks
   \`\`\`

7. **一括操作の確認**

   Ask the user a single confirmation question:

   - "N 件の変更をアーカイブしますか？" をステータスに応じて提示
   - 選択肢の例:
     - "N 件すべてをアーカイブ"
     - "準備完了の N 件のみアーカイブ（未完了は除外）"
     - "キャンセル"

   未完了がある場合は、警告付きでアーカイブされることを明記。

   Route on the answer by intent, not by exact label — you wrote these labels,
   so match what the user picked rather than the wording above:
   - "Cancel" — stop, do not archive. Report that nothing was archived and skip the remaining steps.
   - The archive-everything option — proceed with every selected change
   - The ready-only option — proceed with only the changes the step 6 table marks \`Ready\` or \`Ready*\`, and record the rest as Skipped in step 8d. If a \`Ready*\` change's conflict partner is skipped, re-derive that conflict's resolution using only the changes being archived.
   - Anything else — ask again rather than archiving

   Before step 8 writes the first main spec or moves any change, fetch every
   required specs-rule snapshot for the confirmed batch. For each change that will
   sync concrete \`artifactPaths.specs.existingOutputPaths\`, run
   \`openspec instructions specs --change "<name>" --json\` exactly once with the
   same selected-root flags. Obtain all snapshots before the first write or move.
   If any lookup exits non-zero or returns invalid artifact-instruction JSON,
   identify the affected change, report the error, and stop the whole batch before
   any main-spec write or change move. Do not treat lookup failure as omitted
   rules. A valid response without \`rules\` is the no-rules case.

8. **Execute archive for each confirmed change**

   Before processing, carry the recorded decisions from step 5 (after any step 7 re-derivation) into two per-delta sets:
   - \`includedDeltas\`: all non-conflicting delta specs from confirmed changes plus conflict deltas selected for sync
   - \`excludedDeltas\`: conflict deltas from confirmed changes excluded because their implementation is missing
   - A single change can have both included and excluded delta specs. Keep the decision per delta; do not collapse it into a per-change sync flag.

   Process changes in the determined order (respecting conflict resolution):

   a. **Sync included delta specs**:
      - Run the \`/opsx:sync\` workflow inline (agent-driven intelligent merge) only for changes with entries in \`includedDeltas\`, passing only the included delta paths and explicitly instructing it to ignore that change's \`excludedDeltas\`. Wait for it to finish.
      - For conflicts, apply in resolved order.
      - Pass that change's fetched specs-rule snapshot into inline sync; inline
        sync must reuse it without fetching instructions again
      - Apply artifact rules only to main specs produced by that change. They do
        not change conflict resolution, archive behavior, or CLI contracts, and
        their text is not copied into an output file
      - Do not delegate to a background task — step 8c would move \`changeRoot\` out from under a sync that is still reading it.
      - If a change has no included delta specs, do not run the sync workflow for it.

   b. **Verify included delta specs before moving changeRoot**:
      - Re-run the comparison only for delta specs in \`includedDeltas\` against main spec at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` (use the store-aware \`planningHome.root\` from step 3 status JSON, not a hardcoded repo path).
      - Verify that main specs are updated:
        - ADDED requirements present
        - MODIFIED requirements carrying scenario and description changes named in the delta, with their other scenarios intact
        - REMOVED requirements gone
        - RENAMED requirements present under the new name and absent under the old one
      - Do not verify delta specs in \`excludedDeltas\`; they are intentionally left unsynced.
      - If sync failed or any capability does not match verification, report what differs and fail/skip moving that change's \`changeRoot\` — do not archive that change. \`changeRoot\` remains intact.

   c. **Perform the archive**:

      Target name: use the change name as-is when it already starts with a \`YYYY-MM-DD-\` prefix; otherwise prepend the current date as \`YYYY-MM-DD-<name>\` (same rule as \`openspec archive\`).

      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
      \`\`\`

   d. **Track outcome** for each change:
      - Success: archived successfully
      - Failed: error during archive or spec verification (record error)
      - Skipped: user chose not to archive (if applicable)
      - Sync skipped: for every delta in \`excludedDeltas\`, report \`sync skipped\` with the change, capability, and recorded reason. This is distinct from skipping the archive.

9. **サマリーを表示**

   最終結果を表示:

   \`\`\`markdown
   ## Bulk Archive Complete

   3 件の変更をアーカイブしました:
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   1 件の変更をスキップしました:
   - add-verify-skill（未完了のためユーザーがアーカイブしないことを選択）

   Spec sync summary:
   - 4 delta specs synced to main specs
   - 1 delta spec sync skipped (add-jwt/auth: implementation not found)
   - 1 conflict resolved (auth: synced add-oauth, skipped add-jwt)
   \`\`\`

   If any failures:
   \`\`\`text
   Failed 1 change:
   - some-change: Archive directory already exists
   \`\`\`

**競合解決の例**

Example 1: Only one implemented
\`\`\`text
Conflict: <planningHome.root>/openspec/specs/auth/spec.md touched by [add-oauth, add-jwt]

add-oauth を確認:
- 差分は "OAuth Provider Integration" 要件を追加
- コードベースを検索... OAuth フローを実装する src/auth/oauth.ts を検出

add-jwt を確認:
- 差分は "JWT Token Handling" 要件を追加
- コードベースを検索... JWT 実装は見つからず

解決: add-oauth のみ実装済みです。add-oauth の仕様だけを同期します。
\`\`\`

Example 2: Both implemented
\`\`\`text
Conflict: <planningHome.root>/openspec/specs/api/spec.md touched by [add-rest-api, add-graphql]

add-rest-api を確認（2026-01-10 作成）:
- 差分は "REST Endpoints" 要件を追加
- コードベースを検索... src/api/rest.ts を検出

add-graphql を確認（2026-01-15 作成）:
- 差分は "GraphQL Schema" 要件を追加
- コードベースを検索... src/api/graphql.ts を検出

解決: 両方とも実装済みです。add-rest-api の仕様を先に適用し、
次に add-graphql の仕様を適用します（時系列順。新しいものを優先）。
\`\`\`

**成功時の出力**

\`\`\`markdown
## Bulk Archive Complete

Archived N changes:
- <change-1> -> archive/<target-name-1>/
- <change-2> -> archive/<target-name-2>/

仕様同期サマリー:
- N 件の差分仕様をメイン仕様へ同期
- 競合なし（または: M 件の競合を解決）
\`\`\`

**一部成功時の出力**

\`\`\`markdown
## Bulk Archive Complete (partial)

Archived N changes:
- <change-1> -> archive/<target-name-1>/

M 件の変更をスキップしました:
- <change-2>（未完了のためユーザーがアーカイブしないことを選択）

K 件の変更に失敗しました:
- <change-3>: アーカイブディレクトリが既に存在します
\`\`\`

**変更がない場合の出力**

\`\`\`markdown
## No Changes to Archive

進行中の変更はありません。\`/opsx:new\` で新しい変更を作成してください。
\`\`\`

**Guardrails**
- Allow any number of changes (1+ is fine, 2+ is the typical use case)
- Always prompt for selection, never auto-select
- Detect spec conflicts early and resolve by checking codebase
- When both changes are implemented, apply specs in chronological order
- Skip spec sync only when implementation is missing (warn user)
- Show clear per-change status before confirming
- Use single confirmation for entire batch
- Never archive after the user cancels the confirmation — a cancelled batch archives nothing
- Track and report all outcomes (success/skip/fail)
- Preserve .openspec.yaml when moving to archive
- Archive directory target uses current date: YYYY-MM-DD-<name>; a name that already starts with a \`YYYY-MM-DD-\` prefix is used as-is (never stack a second date)
- If archive target exists, fail that change but continue with others
- If sync is requested, run the \`/opsx:sync\` workflow inline (agent-driven) for each change with included delta specs
- Carry the per-delta \`includedDeltas\` and \`excludedDeltas\` decisions into execution; sync and verify only included deltas
- Report every excluded delta as \`sync skipped\` without treating the archive itself as skipped
- Never archive a change while a spec sync is still in flight — run the sync inline and verify main specs at \`<planningHome.root>/openspec/specs/<capability>/spec.md\` before moving \`changeRoot\`
- Fetch archive inputs once per selected root before spec inspection or moves
- Fetch all required specs-rule snapshots before the batch's first main-spec write or move
- A failed archive-inputs lookup never blocks the batch; it proceeds with no context or guidance
- A failed specs instruction lookup stops the whole batch atomically
- Changes without concrete \`artifactPaths.specs.existingOutputPaths\` continue without spec sync
- Apply relevant runtime context across the batch and report conflicts
- Operation guidance remains advisory; consider every entry and explain rejected advice
- Keep runtime inputs, conflict analysis, CLI-derived values, and artifact rules separate
- Artifact rules constrain only written specs
- Never copy runtime input or artifact-rule text verbatim into output files`
  };
}
