/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-new-change',
    description: 'Start a new OpenSpec change using the experimental artifact workflow. Use when the user wants to create a new feature, fix, or modification with a structured step-by-step approach.',
    instructions: `実験的な成果物主導のアプローチを使用して、新しい変更を開始します。

${STORE_SELECTION_GUIDANCE}

**入力**: ユーザーのリクエストには、変更名 (kebab-case) または構築したい内容の説明を含める必要があります。

**手順**

1. **明確な入力が提供されない場合は、何を構築したいかを尋ねます**

**AskUserQuestion ツール** (自由回答、プリセット オプションなし) を使用して、次のことを質問します。
> 「どのような変更に取り組みたいですか? 何を構築または修正したいのかについて説明してください。」

説明からケバブケース名を導き出します (例: 「ユーザー認証の追加」→ \`add-user-auth\`)。

**重要**: ユーザーが何を構築したいのかを理解せずに先に進まないでください。

2. **ワークフロー スキーマを決定する**

ユーザーが別のワークフローを明示的に要求しない限り、デフォルトのスキーマ (\`--schema\` を省略) を使用します。

**ユーザーが次のことに言及した場合にのみ、別のスキーマを使用します。**
- 特定のスキーマ名 → \`--schema <name>\` を使用します
- 「ワークフローを表示」または「ワークフローの種類」→ \`openspec schemas --json\` を実行して選択させます

**それ以外の場合**: \`--schema\` を省略してデフォルトを使用します。

3. **変更ディレクトリを作成します**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
ユーザーが特定のワークフローを要求した場合にのみ、\`--schema <name>\` を追加します。
これにより、CLI によって解決される計画ホームに足場の変更が作成されます。

4. **アーティファクトのステータスを表示**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
リポジトリ ローカル パスを想定する代わりに、返された \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、および \`nextSteps\` を使用します。

5. **最初のアーティファクトの説明を取得します**
最初のアーティファクトはスキーマに依存します (たとえば、仕様駆動型の場合は \`proposal\`)。
ステータス出力を確認して、ステータスが「準備完了」の最初のアーティファクトを見つけます。
   \`\`\`bash
   openspec instructions <first-artifact-id> --change "<name>"
   \`\`\`
これにより、最初のアーティファクトを作成するためのテンプレートとコンテキストが出力されます。

6. **停止してユーザーの指示を待ちます**

**出力**

手順を完了したら、次のようにまとめます。
- 名前と場所を変更する
- 使用されているスキーマ/ワークフローとそのアーティファクト シーケンス
- 現在のステータス (0/N 個の成果物が完了)
- 最初のアーティファクトのテンプレート
- プロンプト: 「最初のアーティファクトを作成する準備はできましたか? この変更の内容を説明してください。下書きします。または続行するようお願いします。」

**ガードレール**
- まだアーティファクトを作成しないでください。手順を表示するだけにしてください。
- 最初の成果物テンプレートの表示以降は進めないでください。
- 名前が無効な場合 (ケバブケースではない)、有効な名前を尋ねます
- その名前の変更がすでに存在する場合は、代わりにその変更を続行することを提案します
- Pass --schema if using a non-default workflow`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: New',
    description: 'Start a new change using the experimental artifact workflow (OPSX)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `実験的な成果物主導のアプローチを使用して、新しい変更を開始します。

${STORE_SELECTION_GUIDANCE}

**入力**: \`/opsx:new\` の後の引数は、変更名 (kebab-case)、またはユーザーが構築したい内容の説明です。

**手順**

1. **入力が提供されなかった場合は、何を構築したいかを尋ねます**

**AskUserQuestion ツール** (自由回答、プリセット オプションなし) を使用して、次のことを質問します。
> 「どのような変更に取り組みたいですか? 何を構築または修正したいのかについて説明してください。」

説明からケバブケース名を導き出します (例: 「ユーザー認証の追加」→ \`add-user-auth\`)。

**重要**: ユーザーが何を構築したいのかを理解せずに先に進まないでください。

2. **ワークフロー スキーマを決定する**

ユーザーが別のワークフローを明示的に要求しない限り、デフォルトのスキーマ (\`--schema\` を省略) を使用します。

**ユーザーが次のことに言及した場合にのみ、別のスキーマを使用します。**
- 特定のスキーマ名 → \`--schema <name>\` を使用します
- 「ワークフローを表示」または「ワークフローの種類」→ \`openspec schemas --json\` を実行して選択させます

**それ以外の場合**: \`--schema\` を省略してデフォルトを使用します。

3. **変更ディレクトリを作成します**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
ユーザーが特定のワークフローを要求した場合にのみ、\`--schema <name>\` を追加します。
これにより、CLI によって解決される計画ホームに足場の変更が作成されます。

4. **アーティファクトのステータスを表示**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
リポジトリ ローカル パスを想定する代わりに、返された \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、および \`nextSteps\` を使用します。

5. **最初のアーティファクトの説明を取得します**
最初の成果物はスキーマに依存します。ステータス出力を確認して、ステータスが「準備完了」の最初のアーティファクトを見つけます。
   \`\`\`bash
   openspec instructions <first-artifact-id> --change "<name>"
   \`\`\`
これにより、最初のアーティファクトを作成するためのテンプレートとコンテキストが出力されます。

6. **停止してユーザーの指示を待ちます**

**出力**

手順を完了したら、次のようにまとめます。
- 名前と場所を変更する
- 使用されているスキーマ/ワークフローとそのアーティファクト シーケンス
- 現在のステータス (0/N 個の成果物が完了)
- 最初のアーティファクトのテンプレート
- プロンプト: 「最初のアーティファクトを作成する準備はできましたか? \`/opsx:continue\` を実行するか、この変更の内容を説明してください。下書きします。」

**ガードレール**
- まだアーティファクトを作成しないでください。手順を表示するだけにしてください。
- 最初の成果物テンプレートの表示以降は進めないでください。
- 名前が無効な場合 (ケバブケースではない)、有効な名前を尋ねます
- その名前の変更がすでに存在する場合は、代わりに \`/opsx:continue\` を使用することをお勧めします。
- デフォルト以外のワークフローを使用する場合は --schema を渡します`
  };
}
