/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-onboard',
    description: 'Guided onboarding for OpenSpec - walk through a complete workflow cycle with narration and real codebase work.',
    instructions: getOnboardInstructions(),
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

function getOnboardInstructions(): string {
  return `Guide the user through their first complete OpenSpec workflow cycle. This is a teaching experience—you'll do real work in their codebase while explaining each step.

${STORE_SELECTION_GUIDANCE}

---

## Preflight

Before starting, check if the OpenSpec CLI is installed:

\`\`\`bash
# Unix/macOS
openspec --version 2>&1 || echo "CLI_NOT_INSTALLED"
# Windows (PowerShell)
# if (Get-Command openspec -ErrorAction SilentlyContinue) { openspec --version } else { echo "CLI_NOT_INSTALLED" }
\`\`\`

**If CLI not installed:**
> OpenSpec CLI is not installed. Install it first, then come back to \`/opsx:onboard\`.

Stop here if not installed.

---

## Phase 1: Welcome

Display:

\`\`\`
## Welcome to OpenSpec!

I'll walk you through a complete change cycle—from idea to implementation—using a real task in your codebase. Along the way, you'll learn the workflow by doing it.

**What we'll do:**
1. Pick a small, real task in your codebase
2. Explore the problem briefly
3. Create a change (the container for our work)
4. Build the artifacts: proposal → specs → design → tasks
5. Implement the tasks
6. Archive the completed change

**Time:** ~15-20 minutes

Let's start by finding something to work on.
\`\`\`

---

## Phase 2: Task Selection

### Codebase Analysis

Scan the codebase for small improvement opportunities. Look for:

1. **TODO/FIXME comments** - Search for \`TODO\`, \`FIXME\`, \`HACK\`, \`XXX\` in code files
2. **Missing error handling** - \`catch\` blocks that swallow errors, risky operations without try-catch
3. **Functions without tests** - Cross-reference \`src/\` with test directories
4. **Type issues** - \`any\` types in TypeScript files (\`: any\`, \`as any\`)
5. **Debug artifacts** - \`console.log\`, \`console.debug\`, \`debugger\` statements in non-debug code
6. **Missing validation** - User input handlers without validation

Also check recent git activity:
\`\`\`bash
# Unix/macOS
git log --oneline -10 2>/dev/null || echo "No git history"
# Windows (PowerShell)
# git log --oneline -10 2>$null; if ($LASTEXITCODE -ne 0) { echo "No git history" }
\`\`\`

### Present Suggestions

From your analysis, present 3-4 specific suggestions:

\`\`\`
## Task Suggestions

Based on scanning your codebase, here are some good starter tasks:

**1. [Most promising task]**
   Location: \`src/path/to/file.ts:42\`
   Scope: ~1-2 files, ~20-30 lines
   Why it's good: [brief reason]

**2. [Second task]**
   Location: \`src/another/file.ts\`
   Scope: ~1 file, ~15 lines
   Why it's good: [brief reason]

**3. [Third task]**
   Location: [location]
   Scope: [estimate]
   Why it's good: [brief reason]

**4. Something else?**
   Tell me what you'd like to work on.

Which task interests you? (Pick a number or describe your own)
\`\`\`

**見つからない場合:** ユーザーに作りたいものを聞く:
> コードベース内にすぐ着手できそうなものが見つかりませんでした。小さく追加・修正したいことはありますか？

### スコープのガードレール

ユーザーが大きすぎる作業を選んだ場合（大型機能、複数日規模）:

\`\`\`
それは価値のあるタスクですが、最初の OpenSpec 体験には少し大きいかもしれません。

ワークフローを学ぶには、小さい方が全体像を体験しやすく、実装の細部で詰まりにくいです。

**選択肢:**
1. **小さく切る** - [タスク] の最小有用単位は何でしょう？例えば [具体的な切り出し] など？
2. **別のタスクにする** - 他の提案や別の小さなタスク
3. **そのまま進める** - それでも進めたいならOK。ただし時間は長くなります。

どうしますか？
\`\`\`

強く希望するならユーザーの選択を尊重する（これはソフトなガードレール）。

---

## フェーズ 3: Explore デモ

タスクが決まったら、explore モードを簡単に見せる:

\`\`\`
変更を作成する前に、**explore モード**を軽く見せます。方向性を決める前に問題を考えるためのモードです。
\`\`\`

該当コードを 1〜2 分ほど調査する:
- 関連ファイルを読む
- 必要なら簡単な ASCII 図を描く
- 注意点をメモする

\`\`\`
## Quick Exploration

[簡単な分析: 見つけた点、注意点]

┌─────────────────────────────────────────┐
│   [必要なら ASCII 図]                  │
└─────────────────────────────────────────┘

explore モード（\`/opsx:explore\`）は、実装前にこうした調査・思考をするためのものです。必要なときにいつでも使えます。

では、この作業を入れるための change を作成します。
\`\`\`

**PAUSE** - 続行前にユーザーの了承を待つ。

---

## フェーズ 4: 変更を作成

**EXPLAIN:**
\`\`\`
## Creating a Change

OpenSpec の "change" は作業のための箱です。\`openspec/changes/<name>/\` に置かれ、proposal/specs/design/tasks などのアーティファクトを含みます。

では、このタスク用に 1 つ作成します。
\`\`\`

**DO:** kebab-case 名で change を作成:
\`\`\`bash
openspec new change "<derived-name>"
\`\`\`

**SHOW:**
\`\`\`
Created: <changeRoot from status JSON>

The folder structure:
\`\`\`
<changeRoot>/
├── proposal.md    ← Why we're doing this (empty, we'll fill it)
├── design.md      ← How we'll build it (empty)
├── specs/         ← Detailed requirements (empty)
└── tasks.md       ← Implementation checklist (empty)
\`\`\`

では最初のアーティファクト、proposal を作りましょう。
\`\`\`

---

## フェーズ 5: Proposal

**EXPLAIN:**
\`\`\`
## The Proposal

proposal は、この変更を **なぜ** するのか、**何を** するのかを大まかにまとめたものです。作業の "エレベーターピッチ" です。

タスク内容に基づいてドラフトします。
\`\`\`

**DO:** proposal のドラフトを作成（まだ保存しない）:

\`\`\`
Here's a draft proposal:

---

## Why

[1-2 sentences explaining the problem/opportunity]

## What Changes

[Bullet points of what will be different]

## Capabilities

### New Capabilities
- \`<capability-name>\`: [brief description]

### Modified Capabilities
<!-- If modifying existing behavior -->

## Impact

- \`src/path/to/file.ts\`: [what changes]
- [other files if applicable]

---

Does this capture the intent? I can adjust before we save it.
\`\`\`

**PAUSE** - Wait for user approval/feedback.

After approval, save the proposal:
\`\`\`bash
openspec instructions proposal --change "<name>" --json
\`\`\`
Then write the content to the \`resolvedOutputPath\` from \`openspec instructions proposal --change "<name>" --json\`.

\`\`\`
Proposal saved. This is your "why" document—you can always come back and refine it as understanding evolves.

Next up: specs.
\`\`\`

---

## Phase 6: Specs

**EXPLAIN:**
\`\`\`
## Specs

Specs define **what** we're building in precise, testable terms. They use a requirement/scenario format that makes expected behavior crystal clear.

For a small task like this, we might only need one spec file.
\`\`\`

**DO:** Resolve where the spec file should be created:
\`\`\`bash
openspec instructions specs --change "<name>" --json
# Use resolvedOutputPath from the JSON. If it is a glob, choose the concrete file path using the schema instruction and the change's context.
\`\`\`

Draft the spec content:

\`\`\`
Here's the spec:

---

## ADDED Requirements

### Requirement: <Name>

<システムが行うべきことの説明>

#### Scenario: <Scenario name>

- **WHEN** <trigger condition>
- **THEN** <expected outcome>
- **AND** <additional outcome if needed>

---

この WHEN/THEN/AND 形式により、要件をそのままテストケースとして読めます。
\`\`\`

\`openspec/changes/<name>/specs/<capability>/spec.md\` に保存。

---

## フェーズ 7: Design

**EXPLAIN:**
\`\`\`
## Design

design は **どう** 作るかを記録します。技術的な意思決定、トレードオフ、アプローチをまとめます。

小さな変更なら簡潔で構いません。すべての変更で詳細な議論は不要です。
\`\`\`

**DO:** design.md をドラフト:

\`\`\`
Here's the design:

---

## Context

[現状の簡潔な文脈]

## Goals / Non-Goals

**Goals:**
- [達成したいこと]

**Non-Goals:**
- [明確に範囲外とすること]

## Decisions

### Decision 1: [Key decision]

[アプローチと理由]

---

小さなタスクなら、これで十分に意思決定を押さえられます。
\`\`\`

\`openspec/changes/<name>/design.md\` に保存。

---

## フェーズ 8: Tasks

**EXPLAIN:**
\`\`\`
## Tasks

最後に、実装タスクへ分解します。apply フェーズでチェックを付けるタスク一覧です。

小さく、明確で、順序立てて書くことが重要です。
\`\`\`

**DO:** specs/design を元に tasks を作成:

\`\`\`
Here are the implementation tasks:

---

## 1. [Category or file]

- [ ] 1.1 [Specific task]
- [ ] 1.2 [Specific task]

## 2. Verify

- [ ] 2.1 [Verification step]

---

各チェックボックスが apply フェーズの単位作業になります。実装に進めますか？
\`\`\`

**PAUSE** - 実装に進む準備ができたか確認する。

\`openspec/changes/<name>/tasks.md\` に保存。

---

## フェーズ 9: Apply（実装）

**EXPLAIN:**
\`\`\`
## 実装

各タスクを実装しながらチェックを付けていきます。タスクごとに宣言し、必要なら specs/design に触れます。
\`\`\`

**DO:** 各タスクで:

1. 「タスク N に取り組み中: [description]」と宣言
2. コードベースに実装
3. specs/design を自然に参照: 「spec では X とあるので Y を実装」
4. tasks.md を更新: \`- [ ]\` → \`- [x]\`
5. 簡単なステータス: 「✓ タスク N 完了」

説明は軽く。コードの一行ごとに講義しない。

すべて完了したら:

\`\`\`
## 実装完了

すべてのタスクが完了しました:
- [x] Task 1
- [x] Task 2
- [x] ...

変更の実装が完了しました。最後にアーカイブします。
\`\`\`

---

## フェーズ 10: Archive

**EXPLAIN:**
\`\`\`
## アーカイブ中

変更が完了したらアーカイブする。\`openspec/changes/\` から \`openspec/changes/archive/YYYY-MM-DD-<name>/\` に移動される。

アーカイブは意思決定の履歴になる。後から「なぜそう作ったか」を参照できる。
\`\`\`

**DO:**
\`\`\`bash
openspec archive "<name>"
\`\`\`

**SHOW:**
\`\`\`
Archived to: \`<planningHome.changesDir>/archive/YYYY-MM-DD-<name>/\`

The change is now part of your project's history. The code is in your codebase, the decision record is preserved.
\`\`\`

---

## Phase 11: Recap & Next Steps

\`\`\`
## Congratulations!

You just completed a full OpenSpec cycle:

1. **Explore** - Thought through the problem
2. **New** - Created a change container
3. **Proposal** - Captured WHY
4. **Specs** - Defined WHAT in detail
5. **Design** - Decided HOW
6. **Tasks** - Broke it into steps
7. **Apply** - Implemented the work
8. **Archive** - Preserved the record

This same rhythm works for any size change—a small fix or a major feature.

---

## Command Reference

**Core workflow:**

 | Command           | What it does                               |
 |-------------------|--------------------------------------------|
 | \`/opsx:propose\` | Create a change and generate all artifacts |
 | \`/opsx:explore\` | Think through problems before/during work  |
 | \`/opsx:apply\`   | Implement tasks from a change              |
 | \`/opsx:archive\` | Archive a completed change                 |

**Additional commands:**

 | Command            | What it does                                             |
 |--------------------|----------------------------------------------------------|
 | \`/opsx:new\`      | Start a new change, step through artifacts one at a time |
 | \`/opsx:continue\` | Continue working on an existing change                   |
 | \`/opsx:ff\`       | Fast-forward: create all artifacts at once               |
 | \`/opsx:verify\`   | Verify implementation matches artifacts                  |

---

## What's Next?

Try \`/opsx:propose\` on something you actually want to build. You've got the rhythm now!
\`\`\`

---

## Graceful Exit Handling

### User wants to stop mid-way

If the user says they need to stop, want to pause, or seem disengaged:

\`\`\`
No problem! Your change is saved at the \`changeRoot\` reported by \`openspec status --change "<name>" --json\`.

To pick up where we left off later:
- \`/opsx:continue <name>\` - Resume artifact creation
- \`/opsx:apply <name>\` - Jump to implementation (if tasks exist)

The work won't be lost. Come back whenever you're ready.
\`\`\`

Exit gracefully without pressure.

### User just wants command reference

If the user says they just want to see the commands or skip the tutorial:

\`\`\`
## OpenSpec Quick Reference

**Core workflow:**

 | Command                  | What it does                               |
 |--------------------------|--------------------------------------------|
 | \`/opsx:propose <name>\` | Create a change and generate all artifacts |
 | \`/opsx:explore\`        | Think through problems (no code changes)   |
 | \`/opsx:apply <name>\`   | Implement tasks                            |
 | \`/opsx:archive <name>\` | Archive when done                          |

**Additional commands:**

 | Command                   | What it does                        |
 |---------------------------|-------------------------------------|
 | \`/opsx:new <name>\`      | Start a new change, step by step    |
 | \`/opsx:continue <name>\` | Continue an existing change         |
 | \`/opsx:ff <name>\`       | Fast-forward: all artifacts at once |
 | \`/opsx:verify <name>\`   | Verify implementation               |

Try \`/opsx:propose\` to start your first change.
\`\`\`

Exit gracefully.

---

## Guardrails

- **Follow the EXPLAIN → DO → SHOW → PAUSE pattern** at key transitions (after explore, after proposal draft, after tasks, after archive)
- **Keep narration light** during implementation—teach without lecturing
- **Don't skip phases** even if the change is small—the goal is teaching the workflow
- **Pause for acknowledgment** at marked points, but don't over-pause
- **Handle exits gracefully**—never pressure the user to continue
- **Use real codebase tasks**—don't simulate or use fake examples
- **Adjust scope gently**—guide toward smaller tasks but respect user choice`;
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: 'Guided onboarding - walk through a complete OpenSpec workflow cycle with narration',
    category: 'Workflow',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: getOnboardInstructions(),
  };
}
