/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getSyncSpecsSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-sync-specs',
    description: 'Sync delta specs from a change to main specs. Use when the user wants to update main specs with changes from a delta spec, without archiving the change.',
    instructions: `変更からメインスペックへのデルタスペックを同期します。

これは**エージェント主導**の操作です。デルタ仕様を読み取り、メイン仕様を直接編集して変更を適用します。これにより、インテリジェントなマージ (要件全体をコピーせずにシナリオを追加するなど) が可能になります。

${STORE_SELECTION_GUIDANCE}

**入力**: 必要に応じて、変更名を指定します。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更名が指定されていない場合は、選択を求めるプロンプトが表示されます**

\`openspec list --json\` を実行して、利用可能な変更を取得します。 **AskUserQuestion ツール**を使用して、ユーザーに選択させます。

デルタ仕様を含む変更を表示します (\`specs/\` ディレクトリ下)。

**重要**: 変更を推測したり自動選択したりしないでください。常にユーザーに選択してもらいます。

2. **変更コンテキストの解決**

走る：
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`

3. **デルタ仕様を見つける**

デルタ仕様ファイルのリストとしてステータス JSON の \`artifactPaths.specs.existingOutputPaths\` を使用します。

各デルタ仕様ファイルには次のようなセクションが含まれています。
- \`## ADDED Requirements\` - 追加する新しい要件
- \`## MODIFIED Requirements\` - 既存の要件の変更
- \`## REMOVED Requirements\` - 削除の要件
- \`## RENAMED Requirements\` - 名前を変更するための要件 (FROM:/TO: 形式)

デルタ仕様が見つからない場合は、ユーザーに通知して停止します。

4. **デルタ仕様ごとに、メイン仕様に変更を適用します**

CLI によって返される各リポジトリ ローカル機能デルタ仕様パスについては、次のようになります。

ａ． **デルタ仕様を読んで**、意図された変更を理解してください

b. **主な仕様を読んでください**（\`openspec/specs/<capability>/spec.md\`）（まだ存在しない可能性があります）

c. **変更をインテリジェントに適用**:

**追加要件:**
- 主要仕様に要件が存在しない場合 → 追加する
- 要件がすでに存在する場合 → 一致するように更新します (暗黙的な MODIFIED として扱います)

**変更された要件:**
- 主な仕様で要件を見つける
- 変更を適用します。これは次のとおりです。
- 新しいシナリオの追加 (既存のシナリオをコピーする必要はありません)
- 既存のシナリオの変更
- 要件の説明の変更
- デルタに記載されていないシナリオ/コンテンツを保持する

**削除された要件:**
- 主要仕様から要件ブロック全体を削除します。

**名前変更された要件:**
- FROM 要件を見つけて、名前を TO に変更します

d. **機能がまだ存在しない場合は、**新しいメイン仕様を作成**:
- \`openspec/specs/<capability>/spec.md\` を作成する
- 目的セクションを追加 (簡潔にすることもでき、TBD としてマーク)
- 追加された要件を含む「要件を追加」セクション

5. **概要を表示**

すべての変更を適用した後、次のように要約します。
- どの機能が更新されたか
- どのような変更が行われたか (要件の追加/変更/削除/名前変更)

**デルタスペックフォーマットリファレンス**

\`\`\`markdown
## ADDED Requirements

### Requirement: New Feature
The system SHALL do something new.

#### Scenario: Basic case
- **WHEN** user does X
- **THEN** system does Y

## MODIFIED Requirements

### Requirement: Existing Feature
#### Scenario: New scenario to add
- **WHEN** user does A
- **THEN** system does B

## REMOVED Requirements

### Requirement: Deprecated Feature

## RENAMED Requirements

- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

**重要な原則: インテリジェントなマージ**

プログラムによる結合とは異なり、**部分的な更新**を適用できます。
- シナリオを追加するには、そのシナリオを MODIFIED の下に含めるだけです。既存のシナリオをコピーしないでください。
- デルタは *意図* を表しており、大規模な置き換えではありません
- ご自身の判断で変更を賢明にマージしてください

**成功時の出力**

\`\`\`
## Specs Synced: <change-name>

Updated main specs:

**<capability-1>**:
- Added requirement: "New Feature"
- Modified requirement: "Existing Feature" (added 1 scenario)

**<capability-2>**:
- Created new spec file
- Added requirement: "Another Feature"

Main specs are now updated. The change remains active - archive when implementation is complete.
\`\`\`

**ガードレール**
- 変更を加える前に、デルタ仕様とメイン仕様の両方を読んでください。
- デルタに記載されていない既存のコンテンツを保持する
- 不明な点がある場合は、説明を求めます
- 進行中に何を変更しているかを示す
- The operation should be idempotent - running twice should give same result`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxSyncCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Sync',
    description: 'Sync delta specs from a change to main specs',
    category: 'Workflow',
    tags: ['workflow', 'specs', 'experimental'],
    content: `変更からメインスペックへのデルタスペックを同期します。

これは**エージェント主導**の操作です。デルタ仕様を読み取り、メイン仕様を直接編集して変更を適用します。これにより、インテリジェントなマージ (要件全体をコピーせずにシナリオを追加するなど) が可能になります。

${STORE_SELECTION_GUIDANCE}

**入力**: オプションで、\`/opsx:sync\` の後に変更名を指定します (例: \`/opsx:sync add-auth\`)。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

**手順**

1. **変更名が指定されていない場合は、選択を求めるプロンプトが表示されます**

\`openspec list --json\` を実行して、利用可能な変更を取得します。 **AskUserQuestion ツール**を使用して、ユーザーに選択させます。

デルタ仕様を含む変更を表示します (\`specs/\` ディレクトリ下)。

**重要**: 変更を推測したり自動選択したりしないでください。常にユーザーに選択してもらいます。

2. **変更コンテキストの解決**

走る：
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`

3. **デルタ仕様を見つける**

デルタ仕様ファイルのリストとしてステータス JSON の \`artifactPaths.specs.existingOutputPaths\` を使用します。

各デルタ仕様ファイルには次のようなセクションが含まれています。
- \`## ADDED Requirements\` - 追加する新しい要件
- \`## MODIFIED Requirements\` - 既存の要件の変更
- \`## REMOVED Requirements\` - 削除の要件
- \`## RENAMED Requirements\` - 名前を変更するための要件 (FROM:/TO: 形式)

デルタ仕様が見つからない場合は、ユーザーに通知して停止します。

4. **デルタ仕様ごとに、メイン仕様に変更を適用します**

CLI によって返される各リポジトリ ローカル機能デルタ仕様パスについては、次のようになります。

ａ． **デルタ仕様を読んで**、意図された変更を理解してください

b. **主な仕様を読んでください**（\`openspec/specs/<capability>/spec.md\`）（まだ存在しない可能性があります）

c. **変更をインテリジェントに適用**:

**追加要件:**
- 主要仕様に要件が存在しない場合 → 追加する
- 要件がすでに存在する場合 → 一致するように更新します (暗黙的な MODIFIED として扱います)

**変更された要件:**
- 主な仕様で要件を見つける
- 変更を適用します。これは次のとおりです。
- 新しいシナリオの追加 (既存のシナリオをコピーする必要はありません)
- 既存のシナリオの変更
- 要件の説明の変更
- デルタに記載されていないシナリオ/コンテンツを保持する

**削除された要件:**
- 主要仕様から要件ブロック全体を削除します。

**名前変更された要件:**
- FROM 要件を見つけて、名前を TO に変更します

d. **機能がまだ存在しない場合は、**新しいメイン仕様を作成**:
- \`openspec/specs/<capability>/spec.md\` を作成する
- 目的セクションを追加 (簡潔にすることもでき、TBD としてマーク)
- 追加された要件を含む「要件を追加」セクション

5. **概要を表示**

すべての変更を適用した後、次のように要約します。
- どの機能が更新されたか
- どのような変更が行われたか (要件の追加/変更/削除/名前変更)

**デルタスペックフォーマットリファレンス**

\`\`\`markdown
## ADDED Requirements

### Requirement: New Feature
The system SHALL do something new.

#### Scenario: Basic case
- **WHEN** user does X
- **THEN** system does Y

## MODIFIED Requirements

### Requirement: Existing Feature
#### Scenario: New scenario to add
- **WHEN** user does A
- **THEN** system does B

## REMOVED Requirements

### Requirement: Deprecated Feature

## RENAMED Requirements

- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

**重要な原則: インテリジェントなマージ**

プログラムによる結合とは異なり、**部分的な更新**を適用できます。
- シナリオを追加するには、そのシナリオを MODIFIED の下に含めるだけです。既存のシナリオをコピーしないでください。
- デルタは *意図* を表しており、大規模な置き換えではありません
- ご自身の判断で変更を賢明にマージしてください

**成功時の出力**

\`\`\`
## Specs Synced: <change-name>

Updated main specs:

**<capability-1>**:
- Added requirement: "New Feature"
- Modified requirement: "Existing Feature" (added 1 scenario)

**<capability-2>**:
- Created new spec file
- Added requirement: "Another Feature"

Main specs are now updated. The change remains active - archive when implementation is complete.
\`\`\`

**ガードレール**
- 変更を加える前に、デルタ仕様とメイン仕様の両方を読んでください。
- デルタに記載されていない既存のコンテンツを保持する
- 不明な点がある場合は、説明を求めます
- 進行中に何を変更しているかを示す
- 操作は冪等である必要があります - 2 回実行しても同じ結果が得られるはずです`
  };
}
