/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { optionalWorkflow } from '../optional-workflow.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';
import { PROJECT_ROOT_GUARD } from './project-root.js';

/**
 * Passages that hand off to `/opsx:continue` or `/opsx:new`. Neither workflow
 * is in the `core` profile, so each is authored with a CLI fallback and
 * resolved at generation time (see optional-workflow.ts). Shared by both
 * surfaces below so the skill and the command cannot drift apart.
 */
const CONTINUE_SCOPE_NOTE = optionalWorkflow(
  'continue',
  'このワークフローは既存のアーティファクトを修正します。まだ存在しないアーティファクトの作成は `/opsx:continue` で行います。',
  'このワークフローは既存のアーティファクトを修正し、未作成のアーティファクトは作成しません。未作成のものがある場合は、`openspec status --change "<name>" --json` で次のアーティファクトを、`openspec instructions "<artifact-id>" --change "<name>" --json` で作成方法を確認できます。'
);

const CONTINUE_CREATE_THEM = optionalWorkflow(
  'continue',
  '作成用の `/opsx:continue` をユーザーに案内します',
  '作成方法を確認する `openspec instructions "<artifact-id>" --change "<name>" --json` をユーザーに案内します'
);

const CONTINUE_NEXT_STEP = optionalWorkflow(
  'continue',
  '`/opsx:continue` で作成することを提案します',
  '`openspec status --change "<name>" --json` で次のアーティファクトを確認し、作成方法を確認する `openspec instructions "<artifact-id>" --change "<name>" --json` を案内します'
);

const CONTINUE_DEFERRED = optionalWorkflow(
  'continue',
  '`/opsx:continue` に回したもの（ファイルがまだ存在せず、状態が `ready` または `blocked` のアーティファクト。`skipped` は含みません）',
  '未作成のため見送ったもの（ファイルが存在せず、状態が `ready` または `blocked` のアーティファクト。`skipped` は含みません）'
);

const CONTINUE_FRONTIER = optionalWorkflow(
  'continue',
  "`/opsx:continue` の役目です",
  'このワークフローの外で別の手順として行います'
);

/**
 * `apply` and `archive` are in the `core` profile but not guaranteed in a
 * custom one, so their handoffs are resolved the same way.
 */
const APPLY_DELTA_HANDOFF = optionalWorkflow(
  'apply',
  '差分をコードに反映するために `/opsx:apply` を提案します',
  'コードの更新が必要な可能性を伝え、差分の反映を提案します'
);

const APPLY_GUARDRAIL = optionalWorkflow(
  'apply',
  '停止し、`/opsx:apply` を案内します',
  '停止し、修正後の計画にはコード変更が必要で、実装は別の手順で行うことを伝えます'
);

const ARCHIVE_HANDOFF = optionalWorkflow(
  'archive',
  '`/opsx:archive` を提案します',
  '`openspec archive "<name>"` でのアーカイブを提案します'
);

const INTENT_CHANGE_GUARDRAIL = optionalWorkflow(
  'new',
  '`/opsx:new` で新しく始めることを提案します（「更新か新規開始か」の判断）',
  '未使用で区別できる変更名を確認し、代わりに `openspec new change "<new-change-name>"` を提案します（「更新か新規開始か」の判断）'
);

export function getUpdateChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-update-change',
    description: '既存の 計画アーティファクトを修正し、相互の一貫性を保ちながら OpenSpec 変更を更新します。変更計画の見直し、新しい決定の反映、編集後のアーティファクト整合に使用します。「openspec update change」または「opsx update」と依頼された場合にも使用します。生成済みファイルを更新する openspec update CLI コマンドを意図している場合は、代わりにそのコマンドを実行します。コードは編集しません。',
    instructions: `変更の既存の計画成果物を改訂し、一貫性を保ちます。コードは決して編集しないでください。

${STORE_SELECTION_GUIDANCE}

${PROJECT_ROOT_GUARD}

**入力**: 必要に応じて、変更名を指定します。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

${CONTINUE_SCOPE_NOTE}

**手順**

1. **変更を選択する**

   名前が指定されていれば使用します。それ以外の場合:
   - 会話で変更に言及していれば、そのコンテキストから推測する
   - アクティブな変更が1つだけなら自動選択する
   - 曖昧なら \`openspec list --json\` で最近変更された順の一覧を取得し、ユーザーに選択してもらう

   選択を求める際は、最近変更された上位3〜4件を候補として表示し、次を示します:
   - 変更名
   - 状態（例: "0/5 tasks"、"complete"、"no tasks"）
   - 最終更新からの経過（\`lastModified\` フィールド）

ユーザーが更新を希望している可能性が高いため、最後に変更された変更を「(推奨)」としてマークします。

   必ず「使用する変更: <name>」と、変更方法（例: \`/opsx:update <other>\`）を伝えます。

2. **変更の成果物を取得します**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   JSON を解析して現在の状態を把握します。レスポンスには次が含まれます:
   - \`schemaName\`: 使用中のワークフロースキーマ（例: "spec-driven"）
   - \`artifacts\`: 各アーティファクトとその状態（"done"、"skipped"、"ready"、"blocked"）の配列
   - \`isPlanningComplete\`: すべての計画アーティファクトが完了したかを示す真偽値。旧版の CLI では同じ値を \`isComplete\` として公開します。
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、\`actionContext\`: パスとスコープのコンテキスト。リポジトリローカルのパスを想定せず、これらを使用します。

アーティファクト ID とパスはアクティブなスキーマから取得されます。これらを仮定したり、ハードコードされたアーティファクト名に基づいて分岐したりしないでください。カスタム スキーマは変更せずに機能する必要があります。

編集するファイルは \`artifactPaths.<id>.existingOutputPaths\` です。ディスク上に存在する具体的なファイルで、グロブ アーティファクト用にすでにグロブ展開されています (例: \`specs/**/*.md\`)。 \`resolvedOutputPath\` には書き込まないでください。グロブ アーティファクトの場合、それは依然としてグロブ パターンであり、実際のファイルではありません。

3. **リクエストを理解する**
- ユーザーが特定のリビジョン (「デザインは現在 X を使用しています」) を要求した場合、それが編集の開始点となります。
- 「更新」/「これを一貫性のあるものにする」とだけ言われた場合は、それを一貫性のレビューとして扱います。既存の成果物を読み、矛盾、ギャップ、重複がないか相互にチェックします。

4. **読んで調整**
   - リクエストが関与するアーティファクトと、変更の他の既存のアーティファクトを読み取ります。
   - 要求された編集案をファイルではなく会話内で作成し、何が変わるかを明確にします。書き込みはすべて手順 5 で行います。次に、編集案と他のすべての既存アーティファクトを、方向を問わず照合します。後のアーティファクトの編集によって、前のアーティファクトの修正が必要になる場合もあります。ビルド順序は読み取る順序の参考であり、修正対象を制限するものではありません。
   - 現在、矛盾していること、欠落していること、または矛盾していることをすべてメモします。
   - 既存のファイル（\`existingOutputPaths\`）への修正を提案します。既存の出力ファイルがなく、状態が \`ready\` または \`blocked\` のアーティファクトは、その旨を記録し、${CONTINUE_CREATE_THEM}。\`skipped\` のアーティファクトは変更せず、不足として扱ったり continue ワークフローに回したりしません。
   - グロブ アーティファクト（例: \`specs/**/*.md\`）は、1 つ以上のファイルが一致すると \`done\` になります。continue ワークフローが扱うのは \`ready\` のアーティファクトだけです。整合確認で、\`existingOutputPaths\` が空でないグロブ アーティファクトに不足ファイルが見つかった場合:
     1. \`openspec instructions "<artifact-id>" --change "<name>" --json\` を実行し、\`instruction\` と \`template\` を使います。\`context\` と \`rules\` は制約として扱い、ファイルにコピーしません。\`skipped: true\` が返された場合は作成しません。依存ファイルをディスクから読み、スキップされていない必須の依存ファイルがなければ停止し、先に復元するようユーザーに求めます。
     2. \`changeRoot\` 内で \`artifactPaths.<id>.outputPath\` に一致する、まだ存在しない具体的なパスを選びます。親ディレクトリのシンボリックリンクを解決しても \`changeRoot\` 内に収まることを確認します。グロブの \`resolvedOutputPath\` は書き込み先にできません。
     3. 新規ファイルを手順 5 の修正案に含め、ユーザーの確認後にだけ作成します。
     4. 確認後、作成の直前に status と instructions を再取得します。アーティファクトが引き続き対象範囲内で、スキップされておらず、一部のファイルがすでに存在することを確かめ、上記の具体的なパスの確認も繰り返します。
     5. 書き込み先がすでに存在すれば失敗する作成操作を使います。\`instruction\` が別のスキルやコマンドに作成を委ねる場合は、確認済みのパスとこれらのガードレールを守れる場合だけ呼び出し、守れなければ停止します。いずれかの確認に失敗した場合や、承認済みの案が有効でなくなった場合は、既存内容の置き換えや別パスの選択をせずに停止し、ユーザーと調整します。
   - 変更がすでに一貫している場合は、その旨を伝え、修正を提案しません。

5. **一度に 1 つのアーティファクトを確認して適用します**
   - このワークフローのアーティファクトへの書き込みは、すべてこの手順で行います。これより前の手順では編集しません。
   - 手順 4 で作成した要求への編集案も含め、各修正案と理由を示します。ユーザーの確認後にだけ書き込みます。
   - ユーザーがリビジョンを拒否した場合は、リビジョンを書き込まないでください。そのアーティファクトは変更しないでください。
   - 大幅な書き換えが必要な場合は、まずそのアーティファクトのルールとテンプレートを取得します。
     \`\`\`bash
     openspec instructions "<artifact-id>" --change "<name>" --json
     \`\`\`

6. **次のステップを指示します (ガイダンスのみ - 決して行動しないでください)**
   - \`existingOutputPaths\` が空で、状態が \`ready\` または \`blocked\` のアーティファクト -> ${CONTINUE_NEXT_STEP}。
   - 変更が実装済み（タスクがチェック済み / 適用済み） -> コードが修正後の計画と一致しなくなる可能性があります。${APPLY_DELTA_HANDOFF}。
   - すべてが完了し、実装済み -> ${ARCHIVE_HANDOFF}。

**出力**

各呼び出しの後に、以下を表示します。
- どの成果物が改訂されたか (そしてどの改訂案が拒否されたか)
- 一部のファイルがすでに存在していたグロブ アーティファクト配下に作成したファイル
- ${CONTINUE_DEFERRED}
- 変更点と推奨される次のコマンド

**ガードレール**
- 計画アーティファクトだけを扱い、実装コードは決して編集しません。改訂後の計画がコード変更を必要とする場合は${APPLY_GUARDRAIL}。
- \`openspec status\` が報告したアーティファクト ID とパスを使用し、ハードコードされたアーティファクト名で分岐しません。
- \`existingOutputPaths\` にある具体的なファイルだけを編集し、グロブの \`resolvedOutputPath\` には決して書き込みません。
- ビルドの進行地点を先に進めません。\`existingOutputPaths\` が空で、状態が \`ready\` または \`blocked\` のアーティファクトの作成は、${CONTINUE_FRONTIER}。\`skipped\` のアーティファクトは変更しません。新規ファイルを作成できるのは、\`existingOutputPaths\` が空でないグロブ アーティファクト配下の、確認済みの具体的なパスだけです。
- 書き込む前に、すべての編集についてユーザーの確認を得ます。
- 要求が変更の詳細化ではなく *意図* 自体を変える場合は、${INTENT_CHANGE_GUARDRAIL}。`,
    license: 'MIT',
    compatibility: 'OpenSpec CLI が必要です。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxUpdateCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Update',
    description: '変更を更新し、既存の 計画アーティファクトを修正して一貫性を保つ（実験的）',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `変更の既存の計画成果物を改訂し、一貫性を保ちます。コードは決して編集しないでください。

${STORE_SELECTION_GUIDANCE}

${PROJECT_ROOT_GUARD}

**入力**: オプションで、\`/opsx:update\` の後に変更名を指定します (例: \`/opsx:update add-auth\`)。省略した場合は、会話の文脈から推測できるかどうかを確認します。曖昧またはあいまいな場合は、利用可能な変更を要求する必要があります。

${CONTINUE_SCOPE_NOTE}

**手順**

1. **変更を選択する**

   名前が指定されていれば使用します。それ以外の場合:
   - 会話で変更に言及していれば、そのコンテキストから推測する
   - アクティブな変更が1つだけなら自動選択する
   - 曖昧なら \`openspec list --json\` で最近変更された順の一覧を取得し、ユーザーに選択してもらう

   選択を求める際は、最近変更された上位3〜4件を候補として表示し、次を示します:
   - 変更名
   - 状態（例: "0/5 tasks"、"complete"、"no tasks"）
   - 最終更新からの経過（\`lastModified\` フィールド）

ユーザーが更新を希望している可能性が高いため、最後に変更された変更を「(推奨)」としてマークします。

   必ず「使用する変更: <name>」と、変更方法（例: \`/opsx:update <other>\`）を伝えます。

2. **変更の成果物を取得します**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   JSON を解析して現在の状態を把握します。レスポンスには次が含まれます:
   - \`schemaName\`: 使用中のワークフロースキーマ（例: "spec-driven"）
   - \`artifacts\`: 各アーティファクトとその状態（"done"、"skipped"、"ready"、"blocked"）の配列
   - \`isPlanningComplete\`: すべての計画アーティファクトが完了したかを示す真偽値。旧版の CLI では同じ値を \`isComplete\` として公開します。
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\`、\`actionContext\`: パスとスコープのコンテキスト。リポジトリローカルのパスを想定せず、これらを使用します。

アーティファクト ID とパスはアクティブなスキーマから取得されます。これらを仮定したり、ハードコードされたアーティファクト名に基づいて分岐したりしないでください。カスタム スキーマは変更せずに機能する必要があります。

編集するファイルは \`artifactPaths.<id>.existingOutputPaths\` です。ディスク上に存在する具体的なファイルで、グロブ アーティファクト用にすでにグロブ展開されています (例: \`specs/**/*.md\`)。 \`resolvedOutputPath\` には書き込まないでください。グロブ アーティファクトの場合、それは依然としてグロブ パターンであり、実際のファイルではありません。

3. **リクエストを理解する**
- ユーザーが特定のリビジョン (「デザインは現在 X を使用しています」) を要求した場合、それが編集の開始点となります。
- 「更新」/「これを一貫性のあるものにする」とだけ言われた場合は、それを一貫性のレビューとして扱います。既存の成果物を読み、矛盾、ギャップ、重複がないか相互にチェックします。

4. **読んで調整**
   - リクエストが関与するアーティファクトと、変更の他の既存のアーティファクトを読み取ります。
   - 要求された編集案をファイルではなく会話内で作成し、何が変わるかを明確にします。書き込みはすべて手順 5 で行います。次に、編集案と他のすべての既存アーティファクトを、方向を問わず照合します。後のアーティファクトの編集によって、前のアーティファクトの修正が必要になる場合もあります。ビルド順序は読み取る順序の参考であり、修正対象を制限するものではありません。
   - 現在、矛盾していること、欠落していること、または矛盾していることをすべてメモします。
   - 既存のファイル（\`existingOutputPaths\`）への修正を提案します。既存の出力ファイルがなく、状態が \`ready\` または \`blocked\` のアーティファクトは、その旨を記録し、${CONTINUE_CREATE_THEM}。\`skipped\` のアーティファクトは変更せず、不足として扱ったり continue ワークフローに回したりしません。
   - グロブ アーティファクト（例: \`specs/**/*.md\`）は、1 つ以上のファイルが一致すると \`done\` になります。continue ワークフローが扱うのは \`ready\` のアーティファクトだけです。整合確認で、\`existingOutputPaths\` が空でないグロブ アーティファクトに不足ファイルが見つかった場合:
     1. \`openspec instructions "<artifact-id>" --change "<name>" --json\` を実行し、\`instruction\` と \`template\` を使います。\`context\` と \`rules\` は制約として扱い、ファイルにコピーしません。\`skipped: true\` が返された場合は作成しません。依存ファイルをディスクから読み、スキップされていない必須の依存ファイルがなければ停止し、先に復元するようユーザーに求めます。
     2. \`changeRoot\` 内で \`artifactPaths.<id>.outputPath\` に一致する、まだ存在しない具体的なパスを選びます。親ディレクトリのシンボリックリンクを解決しても \`changeRoot\` 内に収まることを確認します。グロブの \`resolvedOutputPath\` は書き込み先にできません。
     3. 新規ファイルを手順 5 の修正案に含め、ユーザーの確認後にだけ作成します。
     4. 確認後、作成の直前に status と instructions を再取得します。アーティファクトが引き続き対象範囲内で、スキップされておらず、一部のファイルがすでに存在することを確かめ、上記の具体的なパスの確認も繰り返します。
     5. 書き込み先がすでに存在すれば失敗する作成操作を使います。\`instruction\` が別のスキルやコマンドに作成を委ねる場合は、確認済みのパスとこれらのガードレールを守れる場合だけ呼び出し、守れなければ停止します。いずれかの確認に失敗した場合や、承認済みの案が有効でなくなった場合は、既存内容の置き換えや別パスの選択をせずに停止し、ユーザーと調整します。
   - 変更がすでに一貫している場合は、その旨を伝え、修正を提案しません。

5. **一度に 1 つのアーティファクトを確認して適用します**
   - このワークフローのアーティファクトへの書き込みは、すべてこの手順で行います。これより前の手順では編集しません。
   - 手順 4 で作成した要求への編集案も含め、各修正案と理由を示します。ユーザーの確認後にだけ書き込みます。
   - ユーザーがリビジョンを拒否した場合は、リビジョンを書き込まないでください。そのアーティファクトは変更しないでください。
   - 大幅な書き換えが必要な場合は、まずそのアーティファクトのルールとテンプレートを取得します。
     \`\`\`bash
     openspec instructions "<artifact-id>" --change "<name>" --json
     \`\`\`

6. **次のステップを指示します (ガイダンスのみ - 決して行動しないでください)**
   - \`existingOutputPaths\` が空で、状態が \`ready\` または \`blocked\` のアーティファクト -> ${CONTINUE_NEXT_STEP}。
   - 変更が実装済み（タスクがチェック済み / 適用済み） -> コードが修正後の計画と一致しなくなる可能性があります。${APPLY_DELTA_HANDOFF}。
   - すべてが完了し、実装済み -> ${ARCHIVE_HANDOFF}。

**出力**

各呼び出しの後に、以下を表示します。
- どの成果物が改訂されたか (そしてどの改訂案が拒否されたか)
- 一部のファイルがすでに存在していたグロブ アーティファクト配下に作成したファイル
- ${CONTINUE_DEFERRED}
- 変更点と推奨される次のコマンド

**ガードレール**
- 計画アーティファクトだけを扱い、実装コードは決して編集しません。改訂後の計画がコード変更を必要とする場合は${APPLY_GUARDRAIL}。
- \`openspec status\` が報告したアーティファクト ID とパスを使用し、ハードコードされたアーティファクト名で分岐しません。
- \`existingOutputPaths\` にある具体的なファイルだけを編集し、グロブの \`resolvedOutputPath\` には決して書き込みません。
- ビルドの進行地点を先に進めません。\`existingOutputPaths\` が空で、状態が \`ready\` または \`blocked\` のアーティファクトの作成は、${CONTINUE_FRONTIER}。\`skipped\` のアーティファクトは変更しません。新規ファイルを作成できるのは、\`existingOutputPaths\` が空でないグロブ アーティファクト配下の、確認済みの具体的なパスだけです。
- 書き込む前に、すべての編集についてユーザーの確認を得ます。
- 要求が変更の詳細化ではなく *意図* 自体を変える場合は、${INTENT_CHANGE_GUARDRAIL}。`
  };
}
