name: tdd
version: 1
description: テスト駆動開発のワークフロー - tests → implementation → docs
artifacts:
  - id: spec
    generates: spec.md
    description: 要件を定義する機能仕様
    template: spec.md
    instruction: |
      作るべきもの（WHAT）を定義する機能仕様を作成します。

      セクション:
      - **Feature**: 機能の目的やユーザー価値の名前/概要
      - **Requirements**: 具体的な要件の一覧。規範文は SHALL/MUST を使用し、文末括弧で明示する。SHOULD/MAY は要件本文では使わず、補足的な注意/参考に限る。
      - **Acceptance Criteria**: WHEN/THEN 形式の検証可能な基準

      要件フォーマット:
      - 各要件は具体的かつテスト可能にする
      - SHALL/MUST/SHOULD/MAY は文末括弧で明示し、語尾は次に揃える: SHALL/MUST = 「〜しなければならない。(SHALL/MUST)」, SHOULD = 「〜すべきである。(SHOULD)」, MAY = 「〜してもよい。(MAY)」。文中に SHALL/MUST/SHOULD/MAY を挿入しない。
      - 受け入れ基準は `#### Scenario: <name>` と WHEN/THEN 形式
      - エッジケースやエラーシナリオを明示
      - すべての要件に最低 1 つのシナリオが必要

      例:
      ```
      ## Feature: ユーザー認証

      ユーザーは安全にログインできる。

      ## Requirements

      ### Requirement: パスワード検証
      システムは最低限のセキュリティ要件を満たすパスワードを検証しなければならない。(SHALL)

      #### Scenario: 有効なパスワードを受け入れる
      - **WHEN** 8 文字以上で大文字/小文字/数字を含む
      - **THEN** パスワードを受け入れる

      #### Scenario: 弱いパスワードを拒否する
      - **WHEN** 8 文字未満である
      - **THEN** システムは「パスワードが短すぎます」を表示する
      ```

      この仕様がテスト作成の基準になります。各シナリオはテストケースです。
    requires: []

  - id: tests
    generates: "tests/*.test.ts"
    description: 実装前に書くテストファイル
    template: test.md
    instruction: |
      実装前にテストを書く（TDD の red フェーズ）。

      ファイル命名:
      - `tests/<feature>.test.ts` として作成
      - 機能ごとに 1 ファイル
      - 仕様に一致した分かりやすい名前を付ける

      テスト構造:
      - 仕様のシナリオに合わせて Given/When/Then 形式で書く
      - 関連するテストは `describe()` ブロックでまとめる
      - 仕様の各シナリオは少なくとも 1 つの `it()` に対応させる

      カバレッジ要件:
      - 仕様の各要件をカバーする
      - 成功パス（正常系）を含める
      - エッジケース（境界条件）を含める
      - エラーシナリオ（不正入力/失敗）を含める
      - 最初はテストが失敗する状態にする（まだ実装しない）

      例:
      ```typescript
      describe('Password validation', () => {
        it('accepts valid password with all requirements', () => {
          // GIVEN すべての要件を満たすパスワード
          const password = 'SecurePass1';
          // WHEN 検証する
          const result = validatePassword(password);
          // THEN 受け入れられる
          expect(result.valid).toBe(true);
        });

        it('rejects password shorter than 8 characters', () => {
          // GIVEN 短いパスワード
          const password = 'Short1';
          // WHEN 検証する
          const result = validatePassword(password);
          // THEN メッセージ付きで拒否される
          expect(result.valid).toBe(false);
          expect(result.error).toBe('パスワードが短すぎます');
        });
      });
      ```

      仕様の要件を厳密に守ること。テストが仕様の検証になります。
    requires:
      - spec

  - id: implementation
    generates: "src/*.ts"
    description: テストを通すための実装コード
    template: implementation.md
    instruction: |
      テストが通る実装を行います（TDD の green フェーズ）。

      TDD の流れ:
      1. テストを実行し、失敗を確認（red）
      2. 1 つのテストだけを通す最小実装を書く
      3. テストを実行し、成功を確認（green）
      4. 必要に応じてリファクタし、green を維持する
      5. 次の失敗テストに進む

      実装ガイドライン:
      - 各テストを通す最小限のコードだけを書く
      - 頻繁にテストを実行して進捗を確認する
      - 関数は小さく、責務を絞る
      - 明確で説明的な名前を使う

      コード構成:
      - `src/<feature>.ts` に実装を作成
      - 公開 API を明確に export
      - 実装詳細は private に保つ
      - 公開関数には JSDoc コメントを付ける

      例:
      ```typescript
      /**
       * パスワードがセキュリティ要件を満たすか検証する。
       * @param password - 検証対象のパスワード
       * @returns valid フラグと任意のエラーを含む結果
       */
      export function validatePassword(password: string): ValidationResult {
        if (password.length < 8) {
          return { valid: false, error: 'パスワードが短すぎます' };
        }
        // ... 追加チェック
        return { valid: true };
      }
      ```

      過剰に作り込まず、テストが求める範囲だけ実装します。
    requires:
      - tests

  - id: docs
    generates: "docs/*.md"
    description: 実装済み機能のドキュメント
    template: docs.md
    instruction: |
      実装した機能をドキュメント化します。

      セクション:
      - **Overview**: 機能の内容と存在理由（1〜2 段落）
      - **Getting Started**: すぐに使うための手順
      - **Examples**: よくあるユースケースのコード例
      - **Reference**: 詳細な API ドキュメントや設定

      ガイドライン:
      - 開発者ではなく利用者向けに書く
      - 最も一般的なユースケースから始める
      - そのまま使えるコード例を載せる
      - すべての設定項目とデフォルト値を記載する
      - 制約や落とし穴を明記する
      - 関連機能や仕様へのリンクを載せる

      例:
      ```markdown
      ## Overview

      パスワード検証は、アカウント作成や変更の前に
      セキュリティ要件を満たしているか確認します。

      ## Getting Started

      検証関数を import して使用します:

      ```typescript
      import { validatePassword } from './password';

      const result = validatePassword('MySecurePass1');
      if (!result.valid) {
        console.error(result.error);
      }
      ```

      ## Examples

      ### Basic validation
      ...

      ### Custom error handling
      ...

      ## Reference

      ### validatePassword(password)

      | Parameter | Type | Description |
      |-----------|------|-------------|
      | password | string | 検証対象のパスワード |

      **Returns**: `{ valid: boolean, error?: string }`
      ```

      要件は spec を、詳細は implementation を参照します。
    requires:
      - implementation

apply:
  requires: [tests]
  tracks: null
  instruction: |
    テストを実行して失敗を確認し、最小限の実装で通します。
    テストが green のままになるようにリファクタします。
