export const agentsTemplate = [
  "# OpenSpec Instructions",
  "",
  "OpenSpec で仕様駆動開発を進める AI コーディングアシスタント向けの指示です。",
  "",
  "## TL;DR Quick Checklist",
  "",
  "- 既存の作業を検索: `openspec spec list --long`, `openspec list`（全文検索が必要な場合のみ `rg`）",
  "- スコープを決定: 新しい機能を追加するのか、既存機能を更新するのか判断する",
  "- 生成する `proposal.md` / `tasks.md` / `design.md` / 仕様差分は日本語で記述し、見出しやキーワード（Requirement/Scenario, WHEN/THEN）は英語のまま維持する。規範文は本文を日本語にし、キーワード (SHALL/MUST/SHOULD) だけ英語で残す。意図的に非規範にする場合のみ should/may を使う",
  "- 一意の `change-id` を決める: kebab-case で動詞始まり（`add-`, `update-`, `remove-`, `refactor-` など）",
  "- ひな形を作成: `proposal.md`, `tasks.md`, 必要に応じた `design.md`、影響する機能別の仕様差分",
  "- 仕様差分を書く: `## ADDED|MODIFIED|REMOVED|RENAMED Requirements` を使い、各要件に最低 1 個の `#### Scenario:` を含める",
  "- 検証する: `openspec validate [change-id] --strict` を実行し、指摘をすべて解消する",
  "- 承認を得る: 提案がレビュー・承認されるまで実装を開始しない",
  "",
  "## Three-Stage Workflow",
  "",
  "### Stage 1: Creating Changes",
  "次のような場合は必ず変更提案を作成します:",
  "- 機能を追加するとき",
  "- API・スキーマなど破壊的な変更を実施するとき",
  "- アーキテクチャや設計パターンを更新するとき",
  "- 挙動が変わる性能最適化を行うとき",
  "- セキュリティパターンを見直すとき",
  "",
  "トリガー例（英語で依頼される想定）:",
  "- \"Help me create a change proposal\"",
  "- \"Help me plan a change\"",
  "- \"Help me create a proposal\"",
  "- \"I want to create a spec proposal\"",
  "- \"I want to create a spec\"",
  "",
  "ゆるい判定基準:",
  "- `proposal`, `change`, `spec` のいずれかを含み",
  "- `create`, `plan`, `make`, `start`, `help` のいずれかと組み合わさっている",
  "",
  "次のような作業は提案を省略して直接修正できます:",
  "- 想定挙動へ戻すバグ修正",
  "- 誤字・書式・コメントの修正",
  "- 破壊的でない依存パッケージ更新",
  "- 設定変更のみ",
  "- 既存挙動をカバーするテスト追加",
  "",
  "**Workflow**",
  "1. `openspec/project.md`、`openspec list`、`openspec list --specs` を確認し、現在の文脈を理解する。",
  "2. 動詞始まりの一意な `change-id` を決め、`openspec/changes/<id>/` に `proposal.md`、`tasks.md`、必要なら `design.md` と仕様差分のひな形を作成する。",
  "3. 仕様差分では `## ADDED|MODIFIED|REMOVED Requirements` 見出しを使い、各要件に最低 1 つの `#### Scenario:` を含める。",
  "4. `openspec validate <id> --strict` を実行し、問題をすべて解決してから提案を共有する。",
  "",
  "### Stage 2: Implementing Changes",
  "次の手順を TODO として順番に完了してください。",
  "1. **proposal.md を読む** - 取り組む内容と背景を把握する。",
  "2. **design.md を読む（存在する場合）** - 技術的判断やトレードオフを確認する。",
  "3. **tasks.md を読む** - 実装チェックリストを取得する。",
  "4. **タスクを順番に実装** - 計画された順番で作業し、不要なスコープ拡大を避ける。",
  "5. **完了を確認** - `tasks.md` の各項目が満たされたことを確認する。",
  "6. **チェックリストを更新** - すべて完了したら `- [x]` に更新し、実態と一致させる。",
  "7. **承認ゲート** - 提案がレビュー・承認されるまで実装を開始しない。",
  "",
  "### Stage 3: Archiving Changes",
  "デプロイ後は別 PR で次を実施します:",
  "- `changes/[name]/` を `changes/archive/YYYY-MM-DD-[name]/` へ移動する",
  "- 機能に変更がある場合は `specs/` を更新する",
  "- ツールのみの変更では `openspec archive <change-id> --skip-specs --yes` を使用（必ず change-id を渡す）",
  "- `openspec validate --strict` を再実行し、アーカイブ済み変更が検証を通過することを確認する",
  "",
  "## Before Any Task",
  "",
  "**Context Checklist:**",
  "- [ ] `specs/[capability]/spec.md` で関連仕様を読む",
  "- [ ] `changes/` にある他の変更と競合しないか確認する",
  "- [ ] `openspec/project.md` でプロジェクト固有の慣習を確認する",
  "- [ ] `openspec list` を実行し、進行中の変更を把握する",
  "- [ ] `openspec list --specs` を実行し、既存機能を確認する",
  "",
  "**Before Creating Specs:**",
  "- 機能が既に存在しないか必ず調べる",
  "- 新規ファイルを増やすより、既存仕様を更新することを優先する",
  "- 現状把握には `openspec show [spec]` を使う",
  "- 要求があいまいな場合は、ひな形作成前に 1〜2 件の確認質問をする",
  "",
  "### Search Guidance",
  "- 仕様一覧: `openspec spec list --long`（スクリプト用途は `--json`）",
  "- 変更一覧: `openspec list`（または非推奨の `openspec change list --json`）",
  "- 詳細表示:",
  "  - Spec: `openspec show <spec-id> --type spec`（必要なら `--json`）",
  "  - Change: `openspec show <change-id> --json --deltas-only`",
  "- 全文検索（ripgrep）: `rg -n \"Requirement:|Scenario:\" openspec/specs`",
  "",
  "## Quick Start",
  "",
  "### CLI Commands",
  "",
  "```",
  "# Essential commands",
  "openspec list                  # List active changes",
  "openspec list --specs          # List specifications",
  "openspec show [item]           # Display change or spec",
  "openspec validate [item]       # Validate changes or specs",
  "openspec archive <change-id> [--yes|-y]   # Archive after deployment (add --yes for non-interactive runs)",
  "",
  "# Project management",
  "openspec init [path]           # Initialize OpenSpec",
  "openspec update [path]         # Update instruction files",
  "",
  "# Interactive mode",
  "openspec show                  # Prompts for selection",
  "openspec validate              # Bulk validation mode",
  "",
  "# Debugging",
  "openspec show [change] --json --deltas-only",
  "openspec validate [change] --strict",
  "```",
  "",
  "### Command Flags",
  "",
  "- `--json` - 機械可読な出力を得る",
  "- `--type change|spec` - 表示対象を明示する",
  "- `--strict` - 厳密検証を有効化する",
  "- `--no-interactive` - プロンプトを無効化する",
  "- `--skip-specs` - アーカイブ時に仕様更新をスキップする",
  "- `--yes`/`-y` - 対話確認を省略する（非対話実行向け）",
  "",
  "## Directory Structure",
  "",
  "```",
  "openspec/",
  "├── project.md              # Project conventions",
  "├── specs/                  # Current truth - what IS built",
  "│   └── [capability]/       # Single focused capability",
  "│       ├── spec.md         # Requirements and scenarios",
  "│       └── design.md       # Technical patterns",
  "├── changes/                # Proposals - what SHOULD change",
  "│   ├── [change-name]/",
  "│   │   ├── proposal.md     # Why, what, impact",
  "│   │   ├── tasks.md        # Implementation checklist",
  "│   │   ├── design.md       # Technical decisions (optional; see criteria)",
  "│   │   └── specs/          # Delta changes",
  "│   │       └── [capability]/",
  "│   │           └── spec.md # ADDED/MODIFIED/REMOVED",
  "│   └── archive/            # Completed changes",
  "```",
  "",
  "## Creating Change Proposals",
  "",
  "### Decision Tree",
  "",
  "```",
  "新しい依頼がありますか？",
  "├─ 仕様通りに戻すバグ修正？ → 直接修正",
  "├─ 誤字・書式・コメント？ → 直接修正  ",
  "├─ 新機能？ → 提案を作成",
  "├─ 破壊的変更？ → 提案を作成",
  "├─ アーキテクチャ変更？ → 提案を作成",
  "└─ あいまいで判断できない？ → 提案を作成（安全策）",
  "```",
  "",
  "### Proposal Structure",
  "",
  "1. **ディレクトリ作成:** `changes/[change-id]/`（kebab-case、動詞始まり、一意）",
  "",
  "2. **proposal.md を記述:**",
  "```markdown",
  "# Change: [変更の概要]",
  "",
  "## Why",
  "[課題や機会を 1〜2 文で記述]",
  "",
  "## What Changes",
  "- [予定している変更を箇条書き]",
  "- [破壊的変更には **BREAKING** を付ける]",
  "",
  "## Impact",
  "- Affected specs: [影響する機能]",
  "- Affected code: [主なコード/システム]",
  "```",
  "",
  "3. **仕様差分を作成:** `specs/[capability]/spec.md`",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: New Feature",
  "システムは...",
  "",
  "#### Scenario: Success case",
  "- **WHEN** ユーザーが操作する",
  "- **THEN** 期待する結果を返す",
  "",
  "## MODIFIED Requirements",
  "### Requirement: Existing Feature",
  "[更新後の全文を記述]",
  "",
  "## REMOVED Requirements",
  "### Requirement: Old Feature",
  "**Reason**: [削除理由]",
  "**Migration**: [移行方法]",
  "```",
  "複数の機能に影響する場合は、`changes/[change-id]/specs/<capability>/spec.md` を機能ごとに作成してください。",
  "",
  "4. **tasks.md を作成:**",
  "```markdown",
  "## 1. Implementation",
  "- [ ] 1.1 データベーススキーマを追加",
  "- [ ] 1.2 API エンドポイントを実装",
  "",
  "## 2. Testing",
  "- [ ] 2.1 単体テストを追加",
  "- [ ] 2.2 統合テストを追加",
  "",
  "## 3. Launch",
  "- [ ] 3.1 デプロイ",
  "- [ ] 3.2 ドキュメント更新",
  "```",
  "",
  "5. **必要な場合のみ design.md を作成:**",
  "次の条件に該当するときは `design.md` を追加し、それ以外では省略できます。",
  "- 複数サービス/モジュールにまたがる変更や新しいアーキテクチャパターン",
  "- 新しい外部依存や大規模なデータモデル変更",
  "- セキュリティ・性能・移行に関する複雑な要件",
  "- 実装前に技術的判断を固めたい曖昧さが残っている",
  "",
  "最小の `design.md` スケルトン:",
  "```markdown",
  "## Context",
  "[背景・制約・関係者]",
  "",
  "## Goals / Non-Goals",
  "- Goals: [...]",
  "- Non-Goals: [...]",
  "",
  "## Decisions",
  "- Decision: [判断と理由]",
  "- Alternatives considered: [比較した選択肢と理由]",
  "",
  "## Risks / Trade-offs",
  "- [リスク] → 対応策",
  "",
  "## Migration Plan",
  "[手順とロールバック方法]",
  "",
  "## Open Questions",
  "- [...]",
  "```",
  "",
  "## Spec File Format",
  "",
  "### Critical: Scenario Formatting",
  "",
  "**正しい例**（#### 見出しを使う）:",
  "```markdown",
"#### Scenario: ログイン成功",
"- **WHEN** 有効な資格情報が入力されたとき",
"- **THEN** JWT トークンを返す",
  "```",
  "",
  "**誤った例**（箇条書きや太字は不可）:",
  "```markdown",
  "- **Scenario: User login**  ❌",
  "**Scenario**: User login     ❌",
  "### Scenario: User login      ❌",
  "```",
  "",
  "すべての要件には最低 1 つのシナリオが必要です。",
  "",
"### Requirement Wording",
"- 規範的な要件は本文を日本語にし、キーワード (SHALL/MUST/SHOULD) だけ英語で残す。意図的に非規範にする場合のみ should/may を使う",
  "",
  "### Delta Operations",
  "",
  "- `## ADDED Requirements` - 新しい機能",
  "- `## MODIFIED Requirements` - 既存挙動の変更",
  "- `## REMOVED Requirements` - 廃止する機能",
  "- `## RENAMED Requirements` - 要件名の変更",
  "",
  "ヘッダー比較は `trim(header)` で行われるため前後の空白は無視されます。",
  "",
  "#### When to use ADDED vs MODIFIED",
  "- ADDED: 既存要件に依存せず成立する新しい機能に使用。例: 「Slash Command Configuration」を追加するなど。",
  "- MODIFIED: 既存要件の挙動・範囲・受け入れ基準を変えるときに使用。見出しからシナリオまで全文を貼り付け、変更後の内容に書き換える。",
  "- RENAMED: 名前だけを変える場合に使用。挙動も変える場合は RENAMED（名称）と MODIFIED（内容）の両方を記載。",
  "",
  "よくある落とし穴: 既存要件を変更していないのに MODIFIED に追記してしまい、アーカイブ時に前の詳細が失われること。既存要件を変えないなら ADDED で新しい要件として追加してください。",
  "",
  "MODIFIED を正しく記述する手順:",
  "1. `openspec/specs/<capability>/spec.md` で該当要件を探す。",
  "2. `### Requirement: ...` からシナリオ末尾までを丸ごとコピーする。",
  "3. `## MODIFIED Requirements` の下に貼り付け、期待する挙動に書き換える。",
  "4. 見出しが完全一致していること（空白無視）と、`#### Scenario:` を最低 1 つ含むことを確認する。",
  "",
  "RENAMED の例:",
  "```markdown",
  "## RENAMED Requirements",
  "- FROM: `### Requirement: Login`",
  "- TO: `### Requirement: User Authentication`",
  "```",
  "",
  "## Troubleshooting",
  "",
  "### Common Errors",
  "",
  "**\"Change must have at least one delta\"**",
  "- `changes/[name]/specs/` に Markdown ファイルがあるか確認",
  "- ファイルが `## ADDED Requirements` などの操作見出しを含んでいるか確認",
  "",
  "**\"Requirement must have at least one scenario\"**",
  "- 各要件に `#### Scenario:` 見出しがあるか確認",
  "- 箇条書きや太字ではなく `####` を使う",
  "",
  "**Silent scenario parsing failures**",
  "- 正しいフォーマットは `#### Scenario: Name`",
  "- デバッグには `openspec show [change] --json --deltas-only` を使用",
  "",
  "### Validation Tips",
  "",
  "```",
  "# 常に厳密検証を使う",
  "openspec validate [change] --strict",
  "",
  "# デルタの解析結果を確認",
  "openspec show [change] --json | jq '.deltas'",
  "",
  "# 特定の要件のみ確認",
  "openspec show [spec] --json -r 1",
  "```",
  "",
  "## Happy Path Script",
  "",
  "```",
  "# 1) 現状を調査",
  "openspec spec list --long",
  "openspec list",
  "# 必要なら全文検索:",
  "# rg -n \"Requirement:|Scenario:\" openspec/specs",
  "# rg -n \"^#|Requirement:\" openspec/changes",
  "",
  "# 2) change-id を決めてひな形を作成",
  "CHANGE=add-two-factor-auth",
  "mkdir -p openspec/changes/$CHANGE/{specs/auth}",
  "printf \"## Why\\n...\\n\\n## What Changes\\n- ...\\n\\n## Impact\\n- ...\\n\" > openspec/changes/$CHANGE/proposal.md",
  "printf \"## 1. Implementation\\n- [ ] 1.1 ...\\n\" > openspec/changes/$CHANGE/tasks.md",
  "",
  "# 3) 仕様差分を追加（例）",
"cat > openspec/changes/$CHANGE/specs/auth/spec.md << 'EOF'",
"## ADDED Requirements",
"### Requirement: Two-Factor Authentication",
"ログイン時にユーザーは第 2 要素を入力する (MUST)。",
"",
"#### Scenario: OTP 必須",
"- **WHEN** 有効な資格情報が入力されたとき",
"- **THEN** OTP による追加認証を求める",
"EOF",
  "",
  "# 4) 検証",
  "openspec validate $CHANGE --strict",
  "```",
  "",
  "## Multi-Capability Example",
  "",
  "```",
  "openspec/changes/add-2fa-notify/",
  "├── proposal.md",
  "├── tasks.md",
  "└── specs/",
  "    ├── auth/",
  "    │   └── spec.md   # ADDED: Two-Factor Authentication",
  "    └── notifications/",
  "        └── spec.md   # ADDED: OTP email notification",
  "```",
  "",
  "auth/spec.md",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: Two-Factor Authentication",
  "...",
  "```",
  "",
  "notifications/spec.md",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: OTP Email Notification",
  "...",
  "```",
  "",
  "## Best Practices",
  "",
  "### Simplicity First",
  "- 追加コードは 100 行未満を目安にする",
  "- 十分な理由が出るまでは単一ファイル実装を優先する",
  "- 明確な根拠なしに新規フレームワークを導入しない",
  "- 読みやすく実績のあるパターンを選ぶ",
  "",
  "### Complexity Triggers",
  "次のような根拠がある場合のみ複雑さを追加してください:",
  "- 現行実装が遅いと示す性能データ",
  "- >1000 ユーザーや >100MB データなど具体的なスケール要件",
  "- 抽象化を必要とする複数の実績ユースケース",
  "",
  "### Clear References",
  "- コード位置は `file.ts:42` の形式で示す",
  "- 仕様は `specs/auth/spec.md` のように参照する",
  "- 関連する変更や PR をリンクする",
  "",
  "### Capability Naming",
  "- 動詞-名詞（例: `user-auth`, `payment-capture`）で命名",
  "- 機能は単一の目的に絞る",
  "- 「10 分で理解できる」ことを目安にする",
  "- 説明に AND が必要なら分割を検討する"
].join("\n");
