export const agentsTemplate = [
  "# OpenSpec Instructions",
  "",
  "OpenSpec で仕様駆動開発を進める AI コーディングアシスタント向けの指示です。",
  "",
  "## TL;DR Quick Checklist",
  "",
  "- 既存の作業を検索: `openspec spec list --long`, `openspec list`（全文検索が必要な場合のみ `rg`）",
  "- スコープを決定: 新しい機能を追加するのか、既存機能を更新するのか判断する",
  "- 生成する `proposal.md` / `tasks.md` / `design.md` / 仕様差分は日本語で記述し、見出しやキーワード（Requirement/Scenario, WHEN/THEN）は英語のまま維持してください。規範文は本文を日本語にし、キーワード (SHALL/MUST/SHOULD) だけ英語で残してください。意図的に非規範にする場合のみ should/may を使ってください。",
  "- 一意の `change-id` を決める: kebab-case で動詞始まり（`add-`, `update-`, `remove-`, `refactor-` など）",
  "- ひな形を作成: `proposal.md`, `tasks.md`, 必要に応じた `design.md`、影響する機能別の仕様差分",
  "- 仕様差分を書く: `## ADDED|MODIFIED|REMOVED|RENAMED Requirements` を使い、各要件に最低 1 個の `#### Scenario:` を含める",
  "- 検証する: `openspec validate [change-id] --strict --no-interactive` を実行し、指摘をすべて解消する",
  "- 承認を得る: 提案がレビュー・承認されるまで実装を開始しない",
  "",
  "## Three-Stage Workflow",
  "",
  "### Stage 1: Creating Changes",
  "次のような場合は必ず変更提案を作成します:",
  "- 機能を追加するとき",
  "- API・スキーマなど破壊的な変更を実施するとき",
  "- アーキテクチャや設計パターンを更新するとき",
  "- 挙動が変わる性能最適化を行うとき",
  "- セキュリティパターンを見直すとき",
  "",
  "トリガー例（英語で依頼される想定）:",
  "- \"Help me create a change proposal\"",
  "- \"Help me plan a change\"",
  "- \"Help me create a proposal\"",
  "- \"I want to create a spec proposal\"",
  "- \"I want to create a spec\"",
  "",
  "ゆるい判定基準:",
  "- `proposal`, `change`, `spec` のいずれかを含み",
  "- `create`, `plan`, `make`, `start`, `help` のいずれかと組み合わさっている",
  "",
  "次のような作業は提案を省略して直接修正できます:",
  "- 想定挙動へ戻すバグ修正",
  "- 誤字・書式・コメントの修正",
  "- 破壊的でない依存パッケージ更新",
  "- 設定変更のみ",
  "- 既存挙動をカバーするテスト追加",
  "",
  "**Workflow**",
  "1. `openspec/project.md`、`openspec list`、`openspec list --specs` を確認し、現在の文脈を理解する。",
  "2. 動詞始まりの一意な `change-id` を決め、`openspec/changes/<id>/` に `proposal.md`、`tasks.md`、必要なら `design.md` と仕様差分のひな形を作成する。",
  "3. 仕様差分では `## ADDED|MODIFIED|REMOVED Requirements` 見出しを使い、各要件に最低 1 つの `#### Scenario:` を含める。",
  "4. `openspec validate <id> --strict --no-interactive` を実行し、問題をすべて解決してから提案を共有する。",
  "",
  "### Stage 2: Implementing Changes",
  "次の手順を TODO として順番に完了してください。",
  "1. **proposal.md を読む** - 取り組む内容と背景を把握する。",
  "2. **design.md を読む（存在する場合）** - 技術的判断やトレードオフを確認する。",
  "3. **tasks.md を読む** - 実装チェックリストを取得する。",
  "4. **タスクを順番に実装** - 計画された順番で作業し、不要なスコープ拡大を避ける。",
  "5. **完了を確認** - `tasks.md` の各項目が満たされたことを確認する。",
  "6. **チェックリストを更新** - すべて完了したら `- [x]` に更新し、実態と一致させる。",
  "7. **承認ゲート** - 提案がレビュー・承認されるまで実装を開始しない。",
  "",
  "### Stage 3: Archiving Changes",
  "デプロイ後は別 PR で次を実施します:",
  "- `changes/[name]/` を `changes/archive/YYYY-MM-DD-[name]/` へ移動する",
  "- 機能に変更がある場合は `specs/` を更新する",
  "- ツールのみの変更では `openspec archive <change-id> --skip-specs --yes` を使用（必ず change-id を渡す）",
  "- `openspec validate --strict --no-interactive` を再実行し、アーカイブ済み変更が検証を通過することを確認する",
  "",
  "## Before Any Task",
  "",
  "**Context Checklist:**",
  "- [ ] `specs/[capability]/spec.md` で関連仕様を読む",
  "- [ ] `changes/` にある他の変更と競合しないか確認する",
  "- [ ] `openspec/project.md` でプロジェクト固有の慣習を確認する",
  "- [ ] `openspec list` を実行し、進行中の変更を把握する",
  "- [ ] `openspec list --specs` を実行し、既存機能を確認する",
  "",
  "**Before Creating Specs:**",
  "- 機能が既に存在しないか必ず調べる",
  "- 新規ファイルを増やすより、既存仕様を更新することを優先する",
  "- 現状把握には `openspec show [spec]` を使う",
  "- 要求があいまいな場合は、ひな形作成前に 1〜2 件の確認質問をする",
  "",
  "### Search Guidance",
  "- 仕様一覧: `openspec spec list --long`（スクリプト用途は `--json`）",
  "- 変更一覧: `openspec list`（または非推奨の `openspec change list --json`）",
  "- 詳細表示:",
  "  - Spec: `openspec show <spec-id> --type spec`（必要なら `--json`）",
  "  - Change: `openspec show <change-id> --json --deltas-only`",
  "- 全文検索（ripgrep）: `rg -n \"Requirement:|Scenario:\" openspec/specs`",
  "",
  "## Quick Start",
  "",
  "### CLI Commands",
  "",
  "```bash",
  "# Essential commands",
  "openspec list                  # List active changes",
  "openspec list --specs          # List specifications",
  "openspec show [item]           # Display change or spec",
  "openspec validate [item]       # Validate changes or specs",
  "openspec archive <change-id> [--yes|-y]   # Archive after deployment (add --yes for non-interactive runs)",
  "",
  "# Project management",
  "openspec init [path]           # Initialize OpenSpec",
  "openspec update [path]         # Update instruction files",
  "",
  "# Interactive mode",
  "openspec show                  # Prompts for selection",
  "openspec validate              # Bulk validation mode",
  "",
  "# Debugging",
  "openspec show [change] --json --deltas-only",
  "openspec validate [change] --strict --no-interactive",
  "```",
  "",
  "### Command Flags",
  "",
  "- `--json` - 機械可読な出力を得る",
  "- `--type change|spec` - 表示対象を明示する",
  "- `--strict` - 厳密検証を有効化する",
  "- `--no-interactive` - プロンプトを無効化する",
  "- `--skip-specs` - アーカイブ時に仕様更新をスキップする",
  "- `--yes`/`-y` - 対話確認を省略する（非対話実行向け）",
  "",
  "## Directory Structure",
  "",
  "```",
  "openspec/",
  "├── project.md              # プロジェクトの慣習",
  "├── specs/                  # 現在の真実 - 実装済みの状態",
  "│   └── [capability]/       # 単一の機能にフォーカス",
  "│       ├── spec.md         # 要件とシナリオ",
  "│       └── design.md       # 技術的なパターン",
  "├── changes/                # 変更提案 - 変更したい内容",
  "│   ├── [change-name]/",
  "│   │   ├── proposal.md     # 理由・変更内容・影響",
  "│   │   ├── tasks.md        # 実装チェックリスト",
  "│   │   ├── design.md       # 技術的判断（任意; 参照基準あり）",
  "│   │   └── specs/          # 仕様差分",
  "│   │       └── [capability]/",
  "│   │           └── spec.md # ADDED/MODIFIED/REMOVED",
  "│   └── archive/            # 完了済み変更",
  "```",
  "",
  "## Creating Change Proposals",
  "",
  "### Decision Tree",
  "",
  "```",
  "新しい依頼がありますか？",
  "├─ 仕様通りに戻すバグ修正？ → 直接修正",
  "├─ 誤字・書式・コメント？ → 直接修正  ",
  "├─ 新機能？ → 提案を作成",
  "├─ 破壊的変更？ → 提案を作成",
  "├─ アーキテクチャ変更？ → 提案を作成",
  "└─ あいまいで判断できない？ → 提案を作成（安全策）",
  "```",
  "",
  "### Proposal Structure",
  "",
  "1. **ディレクトリ作成:** `changes/[change-id]/`（kebab-case、動詞始まり、一意）",
  "",
  "2. **proposal.md を記述:**",
  "```markdown",
  "# Change: [変更の概要]",
  "",
  "## Why",
  "[課題や機会を 1〜2 文で記述する]",
  "",
  "## What Changes",
  "- [予定している変更を箇条書きで書く]",
  "- [破壊的変更には **BREAKING** を付ける]",
  "",
  "## Impact",
  "- Affected specs: [影響する機能を列挙する]",
  "- Affected code: [主なコード/システムを列挙する]",
  "```",
  "",
  "3. **仕様差分を作成:** `specs/[capability]/spec.md`",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: New Feature",
  "システムは新しい機能を提供する MUST。",
  "",
  "#### Scenario: 成功ケース",
  "- **WHEN** ユーザーが操作する",
  "- **THEN** 期待する結果を返す",
  "",
  "## MODIFIED Requirements",
  "### Requirement: Existing Feature",
  "[更新後の全文を記述]",
  "",
  "## REMOVED Requirements",
  "### Requirement: Old Feature",
  "**Reason**: [削除理由]",
  "**Migration**: [移行方法]",
  "```",
  "複数の機能に影響する場合は、`changes/[change-id]/specs/<capability>/spec.md` を機能ごとに作成してください。",
  "",
  "4. **tasks.md を作成:**",
  "```markdown",
  "## 1. 実装",
  "- [ ] 1.1 データベーススキーマを作成する",
  "- [ ] 1.2 API エンドポイントを実装する",
  "- [ ] 1.3 フロントエンドのコンポーネントを追加する",
  "- [ ] 1.4 テストを書く",
  "```",
  "",
  "5. **design.md を必要に応じて作成:**",
  "次のいずれかに該当する場合は `design.md` を作成し、該当しなければ省略します。",
  "- 複数サービス/モジュールに跨る変更、または新しいアーキテクチャパターン",
  "- 新しい外部依存や大きなデータモデル変更",
  "- セキュリティ/性能/移行の複雑性がある",
  "- 実装前に技術的判断が必要な曖昧さがある",
  "",
  "最小 `design.md` スケルトン:",
  "```markdown",
  "## 背景",
  "[背景、制約、関係者]",
  "",
  "## 目標 / 非目標",
  "- 目標: [...]",
  "- 非目標: [...]",
  "",
  "## 判断",
  "- Decision: [何を/なぜ]",
  "- Alternatives considered: [選択肢と理由]",
  "",
  "## リスク / トレードオフ",
  "- [リスク] → 対応策",
  "",
  "## 移行計画",
  "[手順、ロールバック]",
  "",
  "## 未解決の問い",
  "- [...]",
  "```",
  "",
  "## Spec File Format",
  "",
  "### 重要: Scenario フォーマット",
  "",
  "**正しい例**（#### 見出しを使う）:",
  "```markdown",
  "#### Scenario: ログイン成功",
  "- **WHEN** 有効な認証情報が入力されたとき",
  "- **THEN** JWT トークンを返す",
  "```",
  "",
  "**間違い例**（箇条書きや太字は使わない）:",
  "```markdown",
  "- **Scenario: ログイン**  ❌",
  "**Scenario**: ログイン     ❌",
  "### Scenario: ログイン      ❌",
  "```",
  "",
  "各要件には最低 1 つの Scenario が必須です。",
  "",
  "### Requirement の書き方",
  "- 規範的な要件には SHALL/MUST を使う（意図的でない限り should/may を避ける）",
  "",
  "### Delta Operations",
  "",
  "- `## ADDED Requirements` - 新しい機能",
  "- `## MODIFIED Requirements` - 仕様変更",
  "- `## REMOVED Requirements` - 既存機能の廃止",
  "- `## RENAMED Requirements` - 名称変更",
  "",
  "ヘッダーは `trim(header)` で一致判定（前後の空白は無視される）。",
  "",
  "#### ADDED と MODIFIED の使い分け",
  "- ADDED: 新しい機能やサブ機能を追加する場合。既存要件の意味を変えるのではなく、独立した追加であれば ADDED を優先する（例: \"Slash Command Configuration\" を追加）。",
  "- MODIFIED: 既存要件の挙動・範囲・受け入れ条件を変更する場合。更新後の要件全文（見出し＋全シナリオ）を必ず貼り付ける。アーカイブ時に要件全体が置換されるため、部分的な差分は情報欠落につながる。",
  "- RENAMED: 名前だけを変更する場合に使用する。挙動も変える場合は、RENAMED（名前）＋MODIFIED（内容）を新しい名前で用意する。",
  "",
  "よくある落とし穴: MODIFIED に新しい観点を追加するだけで以前の本文を含めないこと。アーカイブ時に以前の詳細が失われます。既存要件を変えていない場合は ADDED に新規要件として追加してください。",
  "",
  "MODIFIED を正しく書く手順:",
  "1) `openspec/specs/<capability>/spec.md` から既存要件を探す。",
  "2) `### Requirement: ...` からシナリオまでの全文をコピーする。",
  "3) `## MODIFIED Requirements` 配下へ貼り付け、更新内容に合わせて編集する。",
  "4) 見出しテキストが完全一致（空白無視）していることと、`#### Scenario:` があることを確認する。",
  "",
  "RENAMED の例:",
  "```markdown",
  "## RENAMED Requirements",
  "- FROM: `### Requirement: Login`",
  "- TO: `### Requirement: User Authentication`",
  "```",
  "",
  "## Troubleshooting",
  "",
  "### よくあるエラー",
  "",
  "**\"Change must have at least one delta\"**",
  "- `changes/[name]/specs/` に .md ファイルがあるか確認する",
  "- ファイルに操作ヘッダー（## ADDED Requirements）があるか確認する",
  "",
  "**\"Requirement must have at least one scenario\"**",
  "- シナリオが `#### Scenario:` 形式か確認する（# は 4 つ）",
  "- シナリオ見出しに箇条書きや太字を使わない",
  "",
  "**Silent scenario parsing failures**",
  "- 厳密な形式が必要: `#### Scenario: Name`",
  "- デバッグ: `openspec show [change] --json --deltas-only`",
  "",
  "### Validation Tips",
  "",
  "```bash",
  "# 可能な限り strict モードで包括的に検証する",
  "openspec validate [change] --strict --no-interactive",
  "",
  "# 仕様差分のパースを確認する",
  "openspec show [change] --json | jq '.deltas'",
  "",
  "# 個別要件を確認する",
  "openspec show [spec] --json -r 1",
  "```",
  "",
  "## Happy Path Script",
  "",
  "```bash",
  "# 1) 現状を把握する",
  "openspec spec list --long",
  "openspec list",
  "# 必要なら全文検索:",
  "# rg -n \"Requirement:|Scenario:\" openspec/specs",
  "# rg -n \"^#|Requirement:\" openspec/changes",
  "",
  "# 2) change-id を決めてひな形を作る",
  "CHANGE=add-two-factor-auth",
  "mkdir -p openspec/changes/$CHANGE/{specs/auth}",
  "printf \"## Why\\n...\\n\\n## What Changes\\n- ...\\n\\n## Impact\\n- ...\\n\" > openspec/changes/$CHANGE/proposal.md",
  "printf \"## 1. Implementation\\n- [ ] 1.1 ...\\n\" > openspec/changes/$CHANGE/tasks.md",
  "",
  "# 3) 仕様差分を追加する（例）",
  "cat > openspec/changes/$CHANGE/specs/auth/spec.md << 'EOF'",
  "## ADDED Requirements",
  "### Requirement: 二要素認証",
  "ユーザーはログイン時に二要素認証を行う MUST。",
  "",
  "#### Scenario: OTP が必要",
  "- **WHEN** 有効な認証情報が入力されたとき",
  "- **THEN** OTP チャレンジが必要になる",
  "EOF",
  "",
  "# 4) 検証する",
  "openspec validate $CHANGE --strict --no-interactive",
  "```",
  "",
  "## Multi-Capability Example",
  "",
  "```",
  "openspec/changes/add-2fa-notify/",
  "├── proposal.md",
  "├── tasks.md",
  "└── specs/",
  "    ├── auth/",
  "    │   └── spec.md   # ADDED: 二要素認証",
  "    └── notifications/",
  "        └── spec.md   # ADDED: OTP メール通知",
  "```",
  "",
  "auth/spec.md",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: 二要素認証",
  "...",
  "```",
  "",
  "notifications/spec.md",
  "```markdown",
  "## ADDED Requirements",
  "### Requirement: OTP メール通知",
  "...",
  "```",
  "",
  "## Best Practices",
  "",
  "### Simplicity First",
  "- 追加コードは 100 行未満を目安にする",
  "- 単一ファイル実装を優先し、必要が出てから分割する",
  "- 明確な理由がないフレームワーク導入は避ける",
  "- 枯れたパターンを優先する",
  "",
  "### Complexity Triggers",
  "次の場合のみ複雑さを追加する:",
  "- 現行が遅いことを示す性能データがある",
  "- 明確なスケール要件がある（>1000 users, >100MB data）",
  "- 複数の実績あるユースケースが抽象化を必要としている",
  "",
  "### Clear References",
  "- コード位置は `file.ts:42` 形式で示す",
  "- 仕様参照は `specs/auth/spec.md` のように書く",
  "- 関連変更や PR をリンクする",
  "",
  "### Capability Naming",
  "- 動詞-名詞で命名する: `user-auth`, `payment-capture`",
  "- 1 つの機能に絞る",
  "- 10 分で理解できる説明を目安にする",
  "- 「AND」が必要な場合は分割を検討する",
  "",
].join("\n");
