name: spec-driven
version: 1
description: OpenSpec の標準ワークフロー - proposal → specs → design → tasks
artifacts:
  - id: proposal
    generates: proposal.md
    description: 変更の概要を示す初期提案ドキュメント
    template: proposal.md
    instruction: |
      この変更がなぜ必要か（WHY）を示す提案ドキュメントを作成します。

      セクション:
      - **Why**: 問題や機会を 1〜2 文で説明します。何を解決するのか、なぜ今なのか。
      - **What Changes**: 変更点の箇条書き。新しい機能/変更/削除を具体的に。破壊的変更は **BREAKING** を付けます。
      - **Capabilities**: 作成/変更する spec を特定します:
        - **New Capabilities**: 追加する機能。各項目は `specs/<name>/spec.md` を新規作成します。kebab-case 名（例: `user-auth`, `data-export`）。
        - **Modified Capabilities**: REQUIREMENTS が変わる既存機能。実装詳細だけの変更なら不要。各項目は差分 spec が必要です。`openspec/specs/` の既存名を確認し、要件変更がなければ空で構いません。
      - **Impact**: 影響するコード/API/依存関係/システム。

      重要: Capabilities セクションは proposal と specs の契約になります。
      既存 spec を調査してから記入してください。ここに列挙した機能ごとに spec ファイルが必要です。

      1〜2 ページで簡潔に。"how" ではなく "why" に集中し、
      実装詳細は design.md に書きます。

      これが基盤です。specs、design、tasks はすべてここに基づきます。
    requires: []

  - id: specs
    generates: "specs/**/*.md"
    description: 変更内容の詳細仕様
    template: spec.md
    instruction: |
      システムが何をすべきか（WHAT）を定義する仕様ファイルを作成します。

      機能/領域ごとに specs/<name>/spec.md を 1 つ作成します。

      Delta operations（## 見出し）:
      - **ADDED Requirements**: 新しい機能
      - **MODIFIED Requirements**: 挙動変更。更新後の全文を必ず含める
      - **REMOVED Requirements**: 廃止。**Reason** と **Migration** を必ず含める
      - **RENAMED Requirements**: 名称変更のみ。FROM:/TO: 形式

      要件フォーマット:
      - 各要件: `### Requirement: <name>` の後に説明
      - 規範文は SHALL/MUST を使用（should/may は避ける）
      - 各シナリオ: `#### Scenario: <name>` と WHEN/THEN 形式
      - **重要**: シナリオは `####` の 4 つハッシュ必須。`###` や箇条書きは黙って無視されます。
      - すべての要件に最低 1 つのシナリオが必要です。

      MODIFIED requirements の手順:
      1. openspec/specs/<capability>/spec.md から既存要件を探す
      2. `### Requirement:` から全シナリオまでのブロックを丸ごとコピー
      3. `## MODIFIED Requirements` の下に貼り付け、変更後の挙動に編集
      4. 見出しテキストが完全一致していること（空白は無視）

      よくある落とし穴: MODIFIED に一部だけ書くと、アーカイブ時に詳細が失われます。
      既存挙動を変えずに追加するだけなら ADDED を使ってください。

      例:
      ```
      ## ADDED Requirements

      ### Requirement: データのエクスポート
      システムはユーザーが CSV でデータをエクスポートできるようにしなければならない。

      #### Scenario: エクスポート成功
      - **WHEN** ユーザーが「エクスポート」ボタンをクリックする
      - **THEN** システムは全ユーザーデータの CSV をダウンロードする

      ## REMOVED Requirements

      ### Requirement: 旧エクスポート
      **Reason**: 新しいエクスポート方式に置き換え
      **Migration**: /api/v2/export の新エンドポイントを使用
      ```

      仕様はテスト可能であるべきです。各シナリオはテストケース候補になります。
    requires:
      - proposal

  - id: design
    generates: design.md
    description: 実装詳細を含む技術設計ドキュメント
    template: design.md
    instruction: |
      この変更をどう実装するか（HOW）を説明する設計ドキュメントを作成します。

      design.md を書くべきとき（該当が 1 つでもあれば作成）:
      - 横断的な変更（複数サービス/モジュール）や新しいアーキテクチャ
      - 新しい外部依存や大きなデータモデル変更
      - セキュリティ/性能/移行の複雑さ
      - 実装前に技術判断が必要な曖昧さ

      セクション:
      - **Context**: 背景、現状、制約、関係者
      - **Goals / Non-Goals**: 実現すること/やらないこと
      - **Decisions**: 主要な技術判断と理由（なぜ X ではなく Y か）。各判断の代替案も含める
      - **Risks / Trade-offs**: 既知のリスクやトレードオフ。形式: [Risk] → Mitigation
      - **Migration Plan**: デプロイ手順、ロールバック戦略（必要な場合）
      - **Open Questions**: 未解決の判断や不明点

      行ごとの実装ではなく、アーキテクチャと方針に集中します。
      動機は proposal を、要件は specs を参照してください。

      良い設計ドキュメントは、技術判断の「なぜ」を説明します。
    requires:
      - proposal

  - id: tasks
    generates: tasks.md
    description: specs と design から導いた実装タスク
    template: tasks.md
    instruction: |
      実装作業を分解したタスクリストを作成します。

      ガイドライン:
      - 関連タスクは ## 番号付き見出しでまとめる
      - 各タスクはチェックボックス: - [ ] X.Y タスク内容
      - 1 セッションで完了できるサイズにする
      - 依存順に並べる（何が先か）

      例:
      ```
      ## 1. セットアップ

      - [ ] 1.1 新しいモジュール構成を作成
      - [ ] 1.2 package.json に依存を追加

      ## 2. コア実装

      - [ ] 2.1 データエクスポート関数を実装
      - [ ] 2.2 CSV 形式のユーティリティを追加
      ```

      何を作るかは specs を、どう作るかは design を参照します。
      各タスクは完了判定できる内容にしてください。
    requires:
      - specs
      - design

apply:
  requires: [tasks]
  tracks: tasks.md
  instruction: |
    コンテキストファイルを読み、未完了タスクを進めながら完了にチェックしてください。
    詰まったり不明点が出たら一旦止めて確認します。
